


'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace LightSwitchApplication

    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
    Partial Public NotInheritable Class Application
        Inherits Global.Microsoft.LightSwitch.Framework.Client.ClientApplication(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass, Global.LightSwitchApplication.DataWorkspace)

        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New(ByVal applicationDefinition As Global.Microsoft.LightSwitch.Model.IApplicationDefinition)
            MyBase.New(applicationDefinition)

            Global.LightSwitchApplication.Application.DetailsClass.Initialize(Me)
        End Sub

        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Application_Initialize()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Application_LoggedIn()
        End Sub
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Shared Shadows ReadOnly Property Current As Global.LightSwitchApplication.Application
            Get
                Return DirectCast(Global.Microsoft.LightSwitch.Framework.Client.ClientApplication(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Current, Global.LightSwitchApplication.Application)
            End Get
        End Property

        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EditableOutfallsGrid_CanRun(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EditableOutfallsGrid_Run(ByRef handled As Boolean)
        End Sub
    
        ''' <summary>
        ''' Opens the ShowEditableOutfallsGrid screen.  If the screen is already opened, it is activated and shown.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub ShowEditableOutfallsGrid()
            DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IClientApplicationDetails).InvokeMethod(Me.Details.Methods.ShowEditableOutfallsGrid)
        End Sub
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EditableMonitoringStationsGrid_CanRun(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EditableMonitoringStationsGrid_Run(ByRef handled As Boolean)
        End Sub
    
        ''' <summary>
        ''' Opens the ShowEditableMonitoringStationsGrid screen.  If the screen is already opened, it is activated and shown.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub ShowEditableMonitoringStationsGrid()
            DirectCast(Me.Details, Global.Microsoft.LightSwitch.Details.Client.IClientApplicationDetails).InvokeMethod(Me.Details.Methods.ShowEditableMonitoringStationsGrid)
        End Sub
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ClientApplicationDetails(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass, Global.LightSwitchApplication.Application.DetailsClass.PropertySet, Global.LightSwitchApplication.Application.DetailsClass.CommandSet, Global.LightSwitchApplication.Application.DetailsClass.MethodSet)

            Shared Sub New()
                Dim initializeCommandEntry = Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties.ShowEditableOutfallsGrid
                Dim initializeMethodEntry = Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties.ShowEditableOutfallsGrid
            End Sub

            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private Shared ReadOnly __ApplicationEntry As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationDetails(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry = _
                New Global.Microsoft.LightSwitch.Details.Framework.Client.ClientApplicationDetails(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.__Application_Initialized, _
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.__Application_LoggedIn)
            Private Shared Sub __Application_Initialized(a As Global.LightSwitchApplication.Application)
                a.Application_Initialize()
            End Sub
            Private Shared Sub __Application_LoggedIn(a As Global.LightSwitchApplication.Application)
                a.Application_LoggedIn()
            End Sub

            Public Sub New()
                MyBase.New()
            End Sub

            Public Shadows ReadOnly Property Properties As Global.LightSwitchApplication.Application.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property

            Public Shadows ReadOnly Property Commands As Global.LightSwitchApplication.Application.DetailsClass.CommandSet
                Get
                    Return MyBase.Commands
                End Get
            End Property

            Public Shadows ReadOnly Property Methods As Global.LightSwitchApplication.Application.DetailsClass.MethodSet
                Get
                    Return MyBase.Methods
                End Get
            End Property

            Protected Overrides Function CreateScreen(ByVal screenName As String, ByVal ParamArray args() As Object) As Global.Microsoft.LightSwitch.Client.IScreenObject
                Select Case screenName
                    Case "EditableOutfallsGrid"
                        Return Global.LightSwitchApplication.EditableOutfallsGrid.CreateInstance()
                    Case "EditableMonitoringStationsGrid"
                        Return Global.LightSwitchApplication.EditableMonitoringStationsGrid.CreateInstance()
                End Select
            
                Return MyBase.CreateScreen(screenName, args)
            End Function
            
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ClientApplicationPropertySet(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)

            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class CommandSet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ClientApplicationCommandSet(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)

                Public ReadOnly Property ShowEditableOutfallsGrid As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties.ShowEditableOutfallsGrid), Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowEditableMonitoringStationsGrid As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties.ShowEditableMonitoringStationsGrid), Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class MethodSet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Client.ClientApplicationMethodSet(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)

                Public ReadOnly Property ShowEditableOutfallsGrid As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties.ShowEditableOutfallsGrid), Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

                Public ReadOnly Property ShowEditableMonitoringStationsGrid As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass)
                    Get
                        Return DirectCast(MyBase.GetItem(Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties.ShowEditableMonitoringStationsGrid), Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass))
                    End Get
                End Property

            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend NotInheritable Class PropertySetProperties

            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend NotInheritable Class CommandSetProperties

                Public Shared ReadOnly ShowEditableOutfallsGrid As New Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowEditableOutfallsGrid",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowEditableOutfallsGrid_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowEditableOutfallsGrid_CreateExecutableObject)
                Private Shared Sub _ShowEditableOutfallsGrid_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowEditableOutfallsGridCommand, sf)
                End Sub
                Private Shared Function _ShowEditableOutfallsGrid_CreateExecutableObject(d As Global.LightSwitchApplication.Application.DetailsClass) As Global.Microsoft.LightSwitch.IExecutable
                    Return DirectCast(d, Global.LightSwitchApplication.Application.DetailsClass).Methods.ShowEditableOutfallsGrid.CreateInvocation(New Object(0 - 1) { })
                End Function

                Public Shared ReadOnly ShowEditableMonitoringStationsGrid As New Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowEditableMonitoringStationsGrid",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowEditableMonitoringStationsGrid_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.CommandSetProperties._ShowEditableMonitoringStationsGrid_CreateExecutableObject)
                Private Shared Sub _ShowEditableMonitoringStationsGrid_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowEditableMonitoringStationsGridCommand, sf)
                End Sub
                Private Shared Function _ShowEditableMonitoringStationsGrid_CreateExecutableObject(d As Global.LightSwitchApplication.Application.DetailsClass) As Global.Microsoft.LightSwitch.IExecutable
                    Return DirectCast(d, Global.LightSwitchApplication.Application.DetailsClass).Methods.ShowEditableMonitoringStationsGrid.CreateInvocation(New Object(0 - 1) { })
                End Function

            End Class

            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend NotInheritable Class MethodSetProperties

                Public Shared ReadOnly ShowEditableOutfallsGrid As New Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowEditableOutfallsGrid",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowEditableOutfallsGrid_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowEditableOutfallsGrid_CanInvoke,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowEditableOutfallsGrid_InvokeMethod)
                Private Shared Sub _ShowEditableOutfallsGrid_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowEditableOutfallsGridMethod, sf)
                End Sub
                Private Shared Function _ShowEditableOutfallsGrid_CanInvoke(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object), ex As Global.System.Exception) As Global.System.Exception
                    Dim result As Boolean = True
                    d.Application.EditableOutfallsGrid_CanRun(result)
                    Return If(result, Nothing, ex)
                End Function
                Private Shared Sub _ShowEditableOutfallsGrid_InvokeMethod(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object))
                    Dim handled As Boolean = False
                    d.Application.EditableOutfallsGrid_Run(handled)
                    If Not handled Then
                        d.ShowScreen("LightSwitchApplication:EditableOutfallsGrid", Function() Global.LightSwitchApplication.EditableOutfallsGrid.CreateInstance(), args)
                    End If
                End Sub
 
                Public Shared ReadOnly ShowEditableMonitoringStationsGrid As New Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Entry( _
                    "ShowEditableMonitoringStationsGrid",
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowEditableMonitoringStationsGrid_Stub,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowEditableMonitoringStationsGrid_CanInvoke,
                    AddressOf Global.LightSwitchApplication.Application.DetailsClass.MethodSetProperties._ShowEditableMonitoringStationsGrid_InvokeMethod)
                Private Shared Sub _ShowEditableMonitoringStationsGrid_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.Application.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data), d As Global.LightSwitchApplication.Application.DetailsClass, sf As Object)
                    c(d, d._ShowEditableMonitoringStationsGridMethod, sf)
                End Sub
                Private Shared Function _ShowEditableMonitoringStationsGrid_CanInvoke(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object), ex As Global.System.Exception) As Global.System.Exception
                    Dim result As Boolean = True
                    d.Application.EditableMonitoringStationsGrid_CanRun(result)
                    Return If(result, Nothing, ex)
                End Function
                Private Shared Sub _ShowEditableMonitoringStationsGrid_InvokeMethod(d As Global.LightSwitchApplication.Application.DetailsClass, args As Global.System.Collections.ObjectModel.ReadOnlyCollection(Of Object))
                    Dim handled As Boolean = False
                    d.Application.EditableMonitoringStationsGrid_Run(handled)
                    If Not handled Then
                        d.ShowScreen("LightSwitchApplication:EditableMonitoringStationsGrid", Function() Global.LightSwitchApplication.EditableMonitoringStationsGrid.CreateInstance(), args)
                    End If
                End Sub
 
            End Class

            Private _ShowEditableOutfallsGridMethod As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowEditableMonitoringStationsGridMethod As Global.Microsoft.LightSwitch.Details.Framework.ApplicationMethod(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowEditableOutfallsGridCommand As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

            Private _ShowEditableMonitoringStationsGridCommand As Global.Microsoft.LightSwitch.Details.Framework.Base.ApplicationCommand(Of Global.LightSwitchApplication.Application, Global.LightSwitchApplication.Application.DetailsClass).Data

        End Class

    End Class

End Namespace
Namespace LightSwitchApplication
    <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> 
    <Global.System.Diagnostics.DebuggerNonUserCode> 
    <Global.System.CodeDom.Compiler.GeneratedCode("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")>
    <Global.System.ComponentModel.Composition.Export(GetType(Global.Microsoft.LightSwitch.Model.IModuleDefinitionLoader))> 
    <Global.Microsoft.LightSwitch.Model.ModuleDefinitionLoader("LightSwitchApplication")>
    Public Class ClientModuleLoader
        Implements Global.Microsoft.LightSwitch.Model.IModuleDefinitionLoader

        Public Function GetModelResourceManager() As Global.System.Resources.ResourceManager Implements Global.Microsoft.LightSwitch.Model.IModuleDefinitionLoader.GetModelResourceManager
            Return Nothing
        End Function

        Public Function LoadModelFragments() As Global.System.Collections.Generic.IEnumerable(Of Global.System.IO.Stream) Implements Global.Microsoft.LightSwitch.Model.IModuleDefinitionLoader.LoadModelFragments
            Dim assembly As Global.System.Reflection.Assembly = Global.System.Reflection.Assembly.GetExecutingAssembly
            Dim streams As New Global.System.Collections.Generic.List(Of Global.System.IO.Stream)

            For Each resourceName as Global.System.String In assembly.GetManifestResourceNames
                If resourceName.EndsWith(".lsml", Global.System.StringComparison.OrdinalIgnoreCase) Then
                    streams.Add(assembly.GetManifestResourceStream(resourceName))
                End If
            Next

            Return streams
        End Function
    End Class
End Namespace
