
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports __SensorPoint = LightSwitchApplication.SensorPoint

Namespace LightSwitchApplication

    #Region "Entities"
    
    ''' <summary>
    ''' No Modeled Description Available
    ''' </summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
    Public NotInheritable Partial Class SensorPoint
        Inherits Global.Microsoft.LightSwitch.Framework.Base.EntityObject(Of __SensorPoint, __SensorPoint.DetailsClass)
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Initializes a new instance of the SensorPoint entity.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New()
            Me.New(Nothing)
        End Sub
    
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New(entitySet As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __SensorPoint))
            MyBase.New(entitySet)
            
            __SensorPoint.DetailsClass.Initialize(Me)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub SensorPoint_Created()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub SensorPoint_AllowSaveWithErrors(ByRef result As Boolean)
        End Sub
    
        #End Region
    
        #Region "Private Properties"
        
        ''' <summary>
        ''' Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property Application As Global.Microsoft.LightSwitch.IApplication(Of Global.LightSwitchApplication.DataWorkspace)
            Get
                Return Global.LightSwitchApplication.Application.Current
            End Get
        End Property
        
        ''' <summary>
        ''' Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property DataWorkspace As Global.LightSwitchApplication.DataWorkspace
            Get
                Return DirectCast(Me.Details.EntitySet.Details.DataService.Details.DataWorkspace, Global.LightSwitchApplication.DataWorkspace)
            End Get
        End Property
        
        #End Region
    
        #Region "Public Properties"
    
        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property ID As Integer
            Get
                Return __SensorPoint.DetailsClass.GetValue(Me, __SensorPoint.DetailsClass.PropertySetProperties.ID)
            End Get
            Set
                __SensorPoint.DetailsClass.SetValue(Me, __SensorPoint.DetailsClass.PropertySetProperties.ID, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ID_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ID_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ID_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property SensorPointID As String
            Get
                Return __SensorPoint.DetailsClass.GetValue(Me, __SensorPoint.DetailsClass.PropertySetProperties.SensorPointID)
            End Get
            Set
                __SensorPoint.DetailsClass.SetValue(Me, __SensorPoint.DetailsClass.PropertySetProperties.SensorPointID, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub SensorPointID_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub SensorPointID_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub SensorPointID_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property AssociatedEntityID As String
            Get
                Return __SensorPoint.DetailsClass.GetValue(Me, __SensorPoint.DetailsClass.PropertySetProperties.AssociatedEntityID)
            End Get
            Set
                __SensorPoint.DetailsClass.SetValue(Me, __SensorPoint.DetailsClass.PropertySetProperties.AssociatedEntityID, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub AssociatedEntityID_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub AssociatedEntityID_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub AssociatedEntityID_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property FeatureKey As String
            Get
                Return __SensorPoint.DetailsClass.GetValue(Me, __SensorPoint.DetailsClass.PropertySetProperties.FeatureKey)
            End Get
            Set
                __SensorPoint.DetailsClass.SetValue(Me, __SensorPoint.DetailsClass.PropertySetProperties.FeatureKey, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub FeatureKey_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub FeatureKey_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub FeatureKey_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property MonitoringStation As Global.LightSwitchApplication.MonitoringStation
            Get
                Return __SensorPoint.DetailsClass.GetValue(Me, __SensorPoint.DetailsClass.PropertySetProperties.MonitoringStation)
            End Get
            Set
                __SensorPoint.DetailsClass.SetValue(Me, __SensorPoint.DetailsClass.PropertySetProperties.MonitoringStation, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub MonitoringStation_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub MonitoringStation_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub MonitoringStation_Changed()
        End Sub

        #End Region
    
        #Region "Details Class"
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of _
                __SensorPoint, _
                __SensorPoint.DetailsClass, _
                __SensorPoint.DetailsClass.IImplementation, _
                __SensorPoint.DetailsClass.PropertySet, _
                Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __SensorPoint, __SensorPoint.DetailsClass), _
                Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __SensorPoint, __SensorPoint.DetailsClass))
    
            Shared Sub New()
                Dim initializeEntry = __SensorPoint.DetailsClass.PropertySetProperties.ID
            End Sub
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private Shared ReadOnly __SensorPointEntry As Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __SensorPoint, __SensorPoint.DetailsClass).Entry = _
                New Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __SensorPoint, __SensorPoint.DetailsClass).Entry( _
                    AddressOf __SensorPoint.DetailsClass.__SensorPoint_CreateNew, _
                    AddressOf __SensorPoint.DetailsClass.__SensorPoint_Created, _
                    AddressOf __SensorPoint.DetailsClass.__SensorPoint_AllowSaveWithErrors)
            Private Shared Function __SensorPoint_CreateNew(es As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __SensorPoint)) As __SensorPoint
                Return New __SensorPoint(es)
            End Function
            Private Shared Sub __SensorPoint_Created(e As __SensorPoint)
                e.SensorPoint_Created()
            End Sub
            Private Shared Function __SensorPoint_AllowSaveWithErrors(e As __SensorPoint) As Boolean
                Dim result As Boolean = False
                e.SensorPoint_AllowSaveWithErrors(result)
                Return result
            End Function
    
            Public Sub New()
                MyBase.New()
            End Sub
    
            Public ReadOnly Shadows Property Commands As Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __SensorPoint, __SensorPoint.DetailsClass)
                Get
                    Return MyBase.Commands
                End Get
            End Property
    
            Public ReadOnly Shadows Property Methods As Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __SensorPoint, __SensorPoint.DetailsClass)
                Get
                    Return MyBase.Methods
                End Get
            End Property
    
            Public ReadOnly Shadows Property Properties As __SensorPoint.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet(Of __SensorPoint, __SensorPoint.DetailsClass)
    
                Public Sub New()
                    MyBase.New()
                End Sub
    
                Public ReadOnly Property ID As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __SensorPoint, __SensorPoint.DetailsClass, Integer)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__SensorPoint.DetailsClass.PropertySetProperties.ID),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __SensorPoint, __SensorPoint.DetailsClass, Integer))
                    End Get
                End Property
                
                Public ReadOnly Property SensorPointID As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __SensorPoint, __SensorPoint.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__SensorPoint.DetailsClass.PropertySetProperties.SensorPointID),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __SensorPoint, __SensorPoint.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property AssociatedEntityID As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __SensorPoint, __SensorPoint.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__SensorPoint.DetailsClass.PropertySetProperties.AssociatedEntityID),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __SensorPoint, __SensorPoint.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property FeatureKey As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __SensorPoint, __SensorPoint.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__SensorPoint.DetailsClass.PropertySetProperties.FeatureKey),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __SensorPoint, __SensorPoint.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property MonitoringStation As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __SensorPoint, __SensorPoint.DetailsClass, Global.LightSwitchApplication.MonitoringStation)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__SensorPoint.DetailsClass.PropertySetProperties.MonitoringStation),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __SensorPoint, __SensorPoint.DetailsClass, Global.LightSwitchApplication.MonitoringStation))
                    End Get
                End Property
                
            End Class
    
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            Public Interface IImplementation
                Inherits Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
                Shadows Property ID As Integer
                Shadows Property SensorPointID As String
                Shadows Property AssociatedEntityID As String
                Shadows Property FeatureKey As String
                Shadows Property MonitoringStation As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
            End Interface
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend Class PropertySetProperties
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly ID As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __SensorPoint, __SensorPoint.DetailsClass, Integer).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __SensorPoint, __SensorPoint.DetailsClass, Integer).Entry( _
                        "ID", _
                        AddressOf __SensorPoint.DetailsClass.PropertySetProperties._ID_Stub, _
                        AddressOf __SensorPoint.DetailsClass.PropertySetProperties._ID_ComputeIsReadOnly, _
                        AddressOf __SensorPoint.DetailsClass.PropertySetProperties._ID_Validate, _
                        AddressOf __SensorPoint.DetailsClass.PropertySetProperties._ID_GetImplementationValue, _
                        AddressOf __SensorPoint.DetailsClass.PropertySetProperties._ID_SetImplementationValue, _
                        AddressOf __SensorPoint.DetailsClass.PropertySetProperties._ID_OnValueChanged)
                Private Shared Sub _ID_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __SensorPoint.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __SensorPoint, __SensorPoint.DetailsClass, Integer).Data), d As __SensorPoint.DetailsClass, sf As Object)
                    c(d, d._ID, sf)
                End Sub
                Private Shared Function _ID_ComputeIsReadOnly(e As __SensorPoint) As Boolean
                    Dim result As Boolean = False
                    e.ID_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _ID_Validate(e As __SensorPoint, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.ID_Validate(r)
                End Sub
                Private Shared Function _ID_GetImplementationValue(d As __SensorPoint.DetailsClass) As Integer
                    Return d.ImplementationEntity.ID
                End Function
                Private Shared Sub _ID_SetImplementationValue(d As __SensorPoint.DetailsClass, v As Integer)
                    d.ImplementationEntity.ID = v
                End Sub
                Private Shared Sub _ID_OnValueChanged(e As __SensorPoint)
                    e.ID_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly SensorPointID As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __SensorPoint, __SensorPoint.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __SensorPoint, __SensorPoint.DetailsClass, String).Entry( _
                        "SensorPointID", _
                        AddressOf __SensorPoint.DetailsClass.PropertySetProperties._SensorPointID_Stub, _
                        AddressOf __SensorPoint.DetailsClass.PropertySetProperties._SensorPointID_ComputeIsReadOnly, _
                        AddressOf __SensorPoint.DetailsClass.PropertySetProperties._SensorPointID_Validate, _
                        AddressOf __SensorPoint.DetailsClass.PropertySetProperties._SensorPointID_GetImplementationValue, _
                        AddressOf __SensorPoint.DetailsClass.PropertySetProperties._SensorPointID_SetImplementationValue, _
                        AddressOf __SensorPoint.DetailsClass.PropertySetProperties._SensorPointID_OnValueChanged)
                Private Shared Sub _SensorPointID_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __SensorPoint.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __SensorPoint, __SensorPoint.DetailsClass, String).Data), d As __SensorPoint.DetailsClass, sf As Object)
                    c(d, d._SensorPointID, sf)
                End Sub
                Private Shared Function _SensorPointID_ComputeIsReadOnly(e As __SensorPoint) As Boolean
                    Dim result As Boolean = False
                    e.SensorPointID_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _SensorPointID_Validate(e As __SensorPoint, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.SensorPointID_Validate(r)
                End Sub
                Private Shared Function _SensorPointID_GetImplementationValue(d As __SensorPoint.DetailsClass) As String
                    Return d.ImplementationEntity.SensorPointID
                End Function
                Private Shared Sub _SensorPointID_SetImplementationValue(d As __SensorPoint.DetailsClass, v As String)
                    d.ImplementationEntity.SensorPointID = v
                End Sub
                Private Shared Sub _SensorPointID_OnValueChanged(e As __SensorPoint)
                    e.SensorPointID_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly AssociatedEntityID As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __SensorPoint, __SensorPoint.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __SensorPoint, __SensorPoint.DetailsClass, String).Entry( _
                        "AssociatedEntityID", _
                        AddressOf __SensorPoint.DetailsClass.PropertySetProperties._AssociatedEntityID_Stub, _
                        AddressOf __SensorPoint.DetailsClass.PropertySetProperties._AssociatedEntityID_ComputeIsReadOnly, _
                        AddressOf __SensorPoint.DetailsClass.PropertySetProperties._AssociatedEntityID_Validate, _
                        AddressOf __SensorPoint.DetailsClass.PropertySetProperties._AssociatedEntityID_GetImplementationValue, _
                        AddressOf __SensorPoint.DetailsClass.PropertySetProperties._AssociatedEntityID_SetImplementationValue, _
                        AddressOf __SensorPoint.DetailsClass.PropertySetProperties._AssociatedEntityID_OnValueChanged)
                Private Shared Sub _AssociatedEntityID_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __SensorPoint.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __SensorPoint, __SensorPoint.DetailsClass, String).Data), d As __SensorPoint.DetailsClass, sf As Object)
                    c(d, d._AssociatedEntityID, sf)
                End Sub
                Private Shared Function _AssociatedEntityID_ComputeIsReadOnly(e As __SensorPoint) As Boolean
                    Dim result As Boolean = False
                    e.AssociatedEntityID_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _AssociatedEntityID_Validate(e As __SensorPoint, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.AssociatedEntityID_Validate(r)
                End Sub
                Private Shared Function _AssociatedEntityID_GetImplementationValue(d As __SensorPoint.DetailsClass) As String
                    Return d.ImplementationEntity.AssociatedEntityID
                End Function
                Private Shared Sub _AssociatedEntityID_SetImplementationValue(d As __SensorPoint.DetailsClass, v As String)
                    d.ImplementationEntity.AssociatedEntityID = v
                End Sub
                Private Shared Sub _AssociatedEntityID_OnValueChanged(e As __SensorPoint)
                    e.AssociatedEntityID_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly FeatureKey As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __SensorPoint, __SensorPoint.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __SensorPoint, __SensorPoint.DetailsClass, String).Entry( _
                        "FeatureKey", _
                        AddressOf __SensorPoint.DetailsClass.PropertySetProperties._FeatureKey_Stub, _
                        AddressOf __SensorPoint.DetailsClass.PropertySetProperties._FeatureKey_ComputeIsReadOnly, _
                        AddressOf __SensorPoint.DetailsClass.PropertySetProperties._FeatureKey_Validate, _
                        AddressOf __SensorPoint.DetailsClass.PropertySetProperties._FeatureKey_GetImplementationValue, _
                        AddressOf __SensorPoint.DetailsClass.PropertySetProperties._FeatureKey_SetImplementationValue, _
                        AddressOf __SensorPoint.DetailsClass.PropertySetProperties._FeatureKey_OnValueChanged)
                Private Shared Sub _FeatureKey_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __SensorPoint.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __SensorPoint, __SensorPoint.DetailsClass, String).Data), d As __SensorPoint.DetailsClass, sf As Object)
                    c(d, d._FeatureKey, sf)
                End Sub
                Private Shared Function _FeatureKey_ComputeIsReadOnly(e As __SensorPoint) As Boolean
                    Dim result As Boolean = False
                    e.FeatureKey_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _FeatureKey_Validate(e As __SensorPoint, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.FeatureKey_Validate(r)
                End Sub
                Private Shared Function _FeatureKey_GetImplementationValue(d As __SensorPoint.DetailsClass) As String
                    Return d.ImplementationEntity.FeatureKey
                End Function
                Private Shared Sub _FeatureKey_SetImplementationValue(d As __SensorPoint.DetailsClass, v As String)
                    d.ImplementationEntity.FeatureKey = v
                End Sub
                Private Shared Sub _FeatureKey_OnValueChanged(e As __SensorPoint)
                    e.FeatureKey_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly MonitoringStation As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __SensorPoint, __SensorPoint.DetailsClass, Global.LightSwitchApplication.MonitoringStation).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __SensorPoint, __SensorPoint.DetailsClass, Global.LightSwitchApplication.MonitoringStation).Entry( _
                        "MonitoringStation", _
                        AddressOf __SensorPoint.DetailsClass.PropertySetProperties._MonitoringStation_Stub, _
                        AddressOf __SensorPoint.DetailsClass.PropertySetProperties._MonitoringStation_ComputeIsReadOnly, _
                        AddressOf __SensorPoint.DetailsClass.PropertySetProperties._MonitoringStation_Validate, _
                        AddressOf __SensorPoint.DetailsClass.PropertySetProperties._MonitoringStation_GetCoreImplementationValue, _
                        AddressOf __SensorPoint.DetailsClass.PropertySetProperties._MonitoringStation_GetImplementationValue, _
                        AddressOf __SensorPoint.DetailsClass.PropertySetProperties._MonitoringStation_SetImplementationValue, _
                        AddressOf __SensorPoint.DetailsClass.PropertySetProperties._MonitoringStation_Refresh, _
                        AddressOf __SensorPoint.DetailsClass.PropertySetProperties._MonitoringStation_OnValueChanged)
                Private Shared Sub _MonitoringStation_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __SensorPoint.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __SensorPoint, __SensorPoint.DetailsClass, Global.LightSwitchApplication.MonitoringStation).Data), d As __SensorPoint.DetailsClass, sf As Object)
                    c(d, d._MonitoringStation, sf)
                End Sub
                Private Shared Function _MonitoringStation_ComputeIsReadOnly(e As __SensorPoint) As Boolean
                    Dim result As Boolean = False
                    e.MonitoringStation_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _MonitoringStation_Validate(e As __SensorPoint, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.MonitoringStation_Validate(r)
                End Sub
                Private Shared Function _MonitoringStation_GetCoreImplementationValue(d as __SensorPoint.DetailsClass) As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
                    Return d.ImplementationEntity.MonitoringStation
                End Function
                Private Shared Function _MonitoringStation_GetImplementationValue(d as __SensorPoint.DetailsClass) As Global.LightSwitchApplication.MonitoringStation
                    Return d.GetImplementationValue(Of Global.LightSwitchApplication.MonitoringStation, Global.LightSwitchApplication.MonitoringStation.DetailsClass)(__SensorPoint.DetailsClass.PropertySetProperties.MonitoringStation, d._MonitoringStation)
                End Function
                Private Shared Sub _MonitoringStation_SetImplementationValue(d As __SensorPoint.DetailsClass, v As Global.LightSwitchApplication.MonitoringStation)
                    d.SetImplementationValue(__SensorPoint.DetailsClass.PropertySetProperties.MonitoringStation, d._MonitoringStation, Sub(i, ev) i.MonitoringStation = ev, v)
                End Sub
                Private Shared Sub _MonitoringStation_Refresh(d As __SensorPoint.DetailsClass)
                    d.RefreshNavigationProperty(__SensorPoint.DetailsClass.PropertySetProperties.MonitoringStation, d._MonitoringStation)
                End Sub
                Private Shared Sub _MonitoringStation_OnValueChanged(e As __SensorPoint)
                    e.MonitoringStation_Changed()
                End Sub
    
            End Class
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _ID As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __SensorPoint, __SensorPoint.DetailsClass, Integer).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _SensorPointID As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __SensorPoint, __SensorPoint.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _AssociatedEntityID As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __SensorPoint, __SensorPoint.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _FeatureKey As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __SensorPoint, __SensorPoint.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _MonitoringStation As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __SensorPoint, __SensorPoint.DetailsClass, Global.LightSwitchApplication.MonitoringStation).Data
            
        End Class
    
        #End Region
    
    End Class
    
    #End Region
End Namespace
