
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports __rt_ProgType = LightSwitchApplication.rt_ProgType

Namespace LightSwitchApplication

    #Region "Entities"
    
    ''' <summary>
    ''' No Modeled Description Available
    ''' </summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
    Public NotInheritable Partial Class rt_ProgType
        Inherits Global.Microsoft.LightSwitch.Framework.Base.EntityObject(Of __rt_ProgType, __rt_ProgType.DetailsClass)
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Initializes a new instance of the rt_ProgType entity.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New()
            Me.New(Nothing)
        End Sub
    
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New(entitySet As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __rt_ProgType))
            MyBase.New(entitySet)
            
            __rt_ProgType.DetailsClass.Initialize(Me)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub rt_ProgType_Created()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub rt_ProgType_AllowSaveWithErrors(ByRef result As Boolean)
        End Sub
    
        #End Region
    
        #Region "Private Properties"
        
        ''' <summary>
        ''' Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property Application As Global.Microsoft.LightSwitch.IApplication(Of Global.LightSwitchApplication.DataWorkspace)
            Get
                Return Global.LightSwitchApplication.Application.Current
            End Get
        End Property
        
        ''' <summary>
        ''' Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property DataWorkspace As Global.LightSwitchApplication.DataWorkspace
            Get
                Return DirectCast(Me.Details.EntitySet.Details.DataService.Details.DataWorkspace, Global.LightSwitchApplication.DataWorkspace)
            End Get
        End Property
        
        #End Region
    
        #Region "Public Properties"
    
        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property id As Integer
            Get
                Return __rt_ProgType.DetailsClass.GetValue(Me, __rt_ProgType.DetailsClass.PropertySetProperties.id)
            End Get
            Set
                __rt_ProgType.DetailsClass.SetValue(Me, __rt_ProgType.DetailsClass.PropertySetProperties.id, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub id_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub id_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub id_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property ProgType As String
            Get
                Return __rt_ProgType.DetailsClass.GetValue(Me, __rt_ProgType.DetailsClass.PropertySetProperties.ProgType)
            End Get
            Set
                __rt_ProgType.DetailsClass.SetValue(Me, __rt_ProgType.DetailsClass.PropertySetProperties.ProgType, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ProgType_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ProgType_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ProgType_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Description As String
            Get
                Return __rt_ProgType.DetailsClass.GetValue(Me, __rt_ProgType.DetailsClass.PropertySetProperties.Description)
            End Get
            Set
                __rt_ProgType.DetailsClass.SetValue(Me, __rt_ProgType.DetailsClass.PropertySetProperties.Description, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Description_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Description_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Description_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property ProjectAndPrograms As Global.Microsoft.LightSwitch.Framework.EntityCollection(Of Global.LightSwitchApplication.ProjectAndProgram)
            Get
                Return __rt_ProgType.DetailsClass.GetValue(Me, __rt_ProgType.DetailsClass.PropertySetProperties.ProjectAndPrograms)
            End Get
        End Property
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property ProjectAndProgramsQuery As Microsoft.LightSwitch.IDataServiceQueryable(Of Global.LightSwitchApplication.ProjectAndProgram)
            Get
                Return __rt_ProgType.DetailsClass.GetQuery(Me, __rt_ProgType.DetailsClass.PropertySetProperties.ProjectAndPrograms)
            End Get
        End Property

        #End Region
    
        #Region "Details Class"
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of _
                __rt_ProgType, _
                __rt_ProgType.DetailsClass, _
                __rt_ProgType.DetailsClass.IImplementation, _
                __rt_ProgType.DetailsClass.PropertySet, _
                Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __rt_ProgType, __rt_ProgType.DetailsClass), _
                Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __rt_ProgType, __rt_ProgType.DetailsClass))
    
            Shared Sub New()
                Dim initializeEntry = __rt_ProgType.DetailsClass.PropertySetProperties.id
            End Sub
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private Shared ReadOnly __rt_ProgTypeEntry As Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __rt_ProgType, __rt_ProgType.DetailsClass).Entry = _
                New Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __rt_ProgType, __rt_ProgType.DetailsClass).Entry( _
                    AddressOf __rt_ProgType.DetailsClass.__rt_ProgType_CreateNew, _
                    AddressOf __rt_ProgType.DetailsClass.__rt_ProgType_Created, _
                    AddressOf __rt_ProgType.DetailsClass.__rt_ProgType_AllowSaveWithErrors)
            Private Shared Function __rt_ProgType_CreateNew(es As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __rt_ProgType)) As __rt_ProgType
                Return New __rt_ProgType(es)
            End Function
            Private Shared Sub __rt_ProgType_Created(e As __rt_ProgType)
                e.rt_ProgType_Created()
            End Sub
            Private Shared Function __rt_ProgType_AllowSaveWithErrors(e As __rt_ProgType) As Boolean
                Dim result As Boolean = False
                e.rt_ProgType_AllowSaveWithErrors(result)
                Return result
            End Function
    
            Public Sub New()
                MyBase.New()
            End Sub
    
            Public ReadOnly Shadows Property Commands As Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __rt_ProgType, __rt_ProgType.DetailsClass)
                Get
                    Return MyBase.Commands
                End Get
            End Property
    
            Public ReadOnly Shadows Property Methods As Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __rt_ProgType, __rt_ProgType.DetailsClass)
                Get
                    Return MyBase.Methods
                End Get
            End Property
    
            Public ReadOnly Shadows Property Properties As __rt_ProgType.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet(Of __rt_ProgType, __rt_ProgType.DetailsClass)
    
                Public Sub New()
                    MyBase.New()
                End Sub
    
                Public ReadOnly Property id As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __rt_ProgType, __rt_ProgType.DetailsClass, Integer)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__rt_ProgType.DetailsClass.PropertySetProperties.id),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __rt_ProgType, __rt_ProgType.DetailsClass, Integer))
                    End Get
                End Property
                
                Public ReadOnly Property ProgType As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __rt_ProgType, __rt_ProgType.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__rt_ProgType.DetailsClass.PropertySetProperties.ProgType),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __rt_ProgType, __rt_ProgType.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Description As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __rt_ProgType, __rt_ProgType.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__rt_ProgType.DetailsClass.PropertySetProperties.Description),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __rt_ProgType, __rt_ProgType.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property ProjectAndPrograms As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __rt_ProgType, __rt_ProgType.DetailsClass, Global.LightSwitchApplication.ProjectAndProgram)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__rt_ProgType.DetailsClass.PropertySetProperties.ProjectAndPrograms),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __rt_ProgType, __rt_ProgType.DetailsClass, Global.LightSwitchApplication.ProjectAndProgram))
                    End Get
                End Property
                
            End Class
    
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            Public Interface IImplementation
                Inherits Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
                Shadows Property id As Integer
                Shadows Property ProgType As String
                Shadows Property Description As String
                Shadows ReadOnly Property ProjectAndPrograms As Global.System.Collections.IEnumerable
    
            End Interface
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend Class PropertySetProperties
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly id As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __rt_ProgType, __rt_ProgType.DetailsClass, Integer).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __rt_ProgType, __rt_ProgType.DetailsClass, Integer).Entry( _
                        "id", _
                        AddressOf __rt_ProgType.DetailsClass.PropertySetProperties._id_Stub, _
                        AddressOf __rt_ProgType.DetailsClass.PropertySetProperties._id_ComputeIsReadOnly, _
                        AddressOf __rt_ProgType.DetailsClass.PropertySetProperties._id_Validate, _
                        AddressOf __rt_ProgType.DetailsClass.PropertySetProperties._id_GetImplementationValue, _
                        AddressOf __rt_ProgType.DetailsClass.PropertySetProperties._id_SetImplementationValue, _
                        AddressOf __rt_ProgType.DetailsClass.PropertySetProperties._id_OnValueChanged)
                Private Shared Sub _id_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __rt_ProgType.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __rt_ProgType, __rt_ProgType.DetailsClass, Integer).Data), d As __rt_ProgType.DetailsClass, sf As Object)
                    c(d, d._id, sf)
                End Sub
                Private Shared Function _id_ComputeIsReadOnly(e As __rt_ProgType) As Boolean
                    Dim result As Boolean = False
                    e.id_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _id_Validate(e As __rt_ProgType, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.id_Validate(r)
                End Sub
                Private Shared Function _id_GetImplementationValue(d As __rt_ProgType.DetailsClass) As Integer
                    Return d.ImplementationEntity.id
                End Function
                Private Shared Sub _id_SetImplementationValue(d As __rt_ProgType.DetailsClass, v As Integer)
                    d.ImplementationEntity.id = v
                End Sub
                Private Shared Sub _id_OnValueChanged(e As __rt_ProgType)
                    e.id_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly ProgType As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __rt_ProgType, __rt_ProgType.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __rt_ProgType, __rt_ProgType.DetailsClass, String).Entry( _
                        "ProgType", _
                        AddressOf __rt_ProgType.DetailsClass.PropertySetProperties._ProgType_Stub, _
                        AddressOf __rt_ProgType.DetailsClass.PropertySetProperties._ProgType_ComputeIsReadOnly, _
                        AddressOf __rt_ProgType.DetailsClass.PropertySetProperties._ProgType_Validate, _
                        AddressOf __rt_ProgType.DetailsClass.PropertySetProperties._ProgType_GetImplementationValue, _
                        AddressOf __rt_ProgType.DetailsClass.PropertySetProperties._ProgType_SetImplementationValue, _
                        AddressOf __rt_ProgType.DetailsClass.PropertySetProperties._ProgType_OnValueChanged)
                Private Shared Sub _ProgType_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __rt_ProgType.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __rt_ProgType, __rt_ProgType.DetailsClass, String).Data), d As __rt_ProgType.DetailsClass, sf As Object)
                    c(d, d._ProgType, sf)
                End Sub
                Private Shared Function _ProgType_ComputeIsReadOnly(e As __rt_ProgType) As Boolean
                    Dim result As Boolean = False
                    e.ProgType_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _ProgType_Validate(e As __rt_ProgType, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.ProgType_Validate(r)
                End Sub
                Private Shared Function _ProgType_GetImplementationValue(d As __rt_ProgType.DetailsClass) As String
                    Return d.ImplementationEntity.ProgType
                End Function
                Private Shared Sub _ProgType_SetImplementationValue(d As __rt_ProgType.DetailsClass, v As String)
                    d.ImplementationEntity.ProgType = v
                End Sub
                Private Shared Sub _ProgType_OnValueChanged(e As __rt_ProgType)
                    e.ProgType_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Description As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __rt_ProgType, __rt_ProgType.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __rt_ProgType, __rt_ProgType.DetailsClass, String).Entry( _
                        "Description", _
                        AddressOf __rt_ProgType.DetailsClass.PropertySetProperties._Description_Stub, _
                        AddressOf __rt_ProgType.DetailsClass.PropertySetProperties._Description_ComputeIsReadOnly, _
                        AddressOf __rt_ProgType.DetailsClass.PropertySetProperties._Description_Validate, _
                        AddressOf __rt_ProgType.DetailsClass.PropertySetProperties._Description_GetImplementationValue, _
                        AddressOf __rt_ProgType.DetailsClass.PropertySetProperties._Description_SetImplementationValue, _
                        AddressOf __rt_ProgType.DetailsClass.PropertySetProperties._Description_OnValueChanged)
                Private Shared Sub _Description_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __rt_ProgType.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __rt_ProgType, __rt_ProgType.DetailsClass, String).Data), d As __rt_ProgType.DetailsClass, sf As Object)
                    c(d, d._Description, sf)
                End Sub
                Private Shared Function _Description_ComputeIsReadOnly(e As __rt_ProgType) As Boolean
                    Dim result As Boolean = False
                    e.Description_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Description_Validate(e As __rt_ProgType, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Description_Validate(r)
                End Sub
                Private Shared Function _Description_GetImplementationValue(d As __rt_ProgType.DetailsClass) As String
                    Return d.ImplementationEntity.Description
                End Function
                Private Shared Sub _Description_SetImplementationValue(d As __rt_ProgType.DetailsClass, v As String)
                    d.ImplementationEntity.Description = v
                End Sub
                Private Shared Sub _Description_OnValueChanged(e As __rt_ProgType)
                    e.Description_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly ProjectAndPrograms As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __rt_ProgType, __rt_ProgType.DetailsClass, Global.LightSwitchApplication.ProjectAndProgram).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __rt_ProgType, __rt_ProgType.DetailsClass, Global.LightSwitchApplication.ProjectAndProgram).Entry( _
                        "ProjectAndPrograms", _
                        AddressOf __rt_ProgType.DetailsClass.PropertySetProperties._ProjectAndPrograms_Stub, _
                        AddressOf __rt_ProgType.DetailsClass.PropertySetProperties._ProjectAndPrograms_GetReferencedEntities, _
                        AddressOf __rt_ProgType.DetailsClass.PropertySetProperties._ProjectAndPrograms_GetEntityCollection)
                Private Shared Sub _ProjectAndPrograms_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __rt_ProgType.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __rt_ProgType, __rt_ProgType.DetailsClass, Global.LightSwitchApplication.ProjectAndProgram).Data), d As __rt_ProgType.DetailsClass, sf As Object)
                    c(d, d._ProjectAndPrograms, sf)
                End Sub
                Private Shared Function _ProjectAndPrograms_GetReferencedEntities(d As __rt_ProgType.DetailsClass) As Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.ProjectAndProgram)
                    Return d.GetReferencedEntities(Of Global.LightSwitchApplication.ProjectAndProgram, Global.LightSwitchApplication.ProjectAndProgram.DetailsClass)(__rt_ProgType.DetailsClass.PropertySetProperties.ProjectAndPrograms, d._ProjectAndPrograms)
                End Function
                Private Shared Function _ProjectAndPrograms_GetEntityCollection(d As __rt_ProgType.DetailsClass) As Global.System.Collections.IEnumerable
                    Return d.ImplementationEntity.ProjectAndPrograms
                End Function
    
            End Class
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _id As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __rt_ProgType, __rt_ProgType.DetailsClass, Integer).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _ProgType As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __rt_ProgType, __rt_ProgType.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Description As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __rt_ProgType, __rt_ProgType.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _ProjectAndPrograms As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __rt_ProgType, __rt_ProgType.DetailsClass, Global.LightSwitchApplication.ProjectAndProgram).Data
            
        End Class
    
        #End Region
    
    End Class
    
    #End Region
End Namespace
