
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports __rt_Purpose = LightSwitchApplication.rt_Purpose

Namespace LightSwitchApplication

    #Region "Entities"
    
    ''' <summary>
    ''' No Modeled Description Available
    ''' </summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
    Public NotInheritable Partial Class rt_Purpose
        Inherits Global.Microsoft.LightSwitch.Framework.Base.EntityObject(Of __rt_Purpose, __rt_Purpose.DetailsClass)
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Initializes a new instance of the rt_Purpose entity.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New()
            Me.New(Nothing)
        End Sub
    
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New(entitySet As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __rt_Purpose))
            MyBase.New(entitySet)
            
            __rt_Purpose.DetailsClass.Initialize(Me)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub rt_Purpose_Created()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub rt_Purpose_AllowSaveWithErrors(ByRef result As Boolean)
        End Sub
    
        #End Region
    
        #Region "Private Properties"
        
        ''' <summary>
        ''' Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property Application As Global.Microsoft.LightSwitch.IApplication(Of Global.LightSwitchApplication.DataWorkspace)
            Get
                Return Global.LightSwitchApplication.Application.Current
            End Get
        End Property
        
        ''' <summary>
        ''' Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property DataWorkspace As Global.LightSwitchApplication.DataWorkspace
            Get
                Return DirectCast(Me.Details.EntitySet.Details.DataService.Details.DataWorkspace, Global.LightSwitchApplication.DataWorkspace)
            End Get
        End Property
        
        #End Region
    
        #Region "Public Properties"
    
        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property id As Integer
            Get
                Return __rt_Purpose.DetailsClass.GetValue(Me, __rt_Purpose.DetailsClass.PropertySetProperties.id)
            End Get
            Set
                __rt_Purpose.DetailsClass.SetValue(Me, __rt_Purpose.DetailsClass.PropertySetProperties.id, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub id_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub id_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub id_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Purpose As String
            Get
                Return __rt_Purpose.DetailsClass.GetValue(Me, __rt_Purpose.DetailsClass.PropertySetProperties.Purpose)
            End Get
            Set
                __rt_Purpose.DetailsClass.SetValue(Me, __rt_Purpose.DetailsClass.PropertySetProperties.Purpose, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Purpose_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Purpose_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Purpose_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Description As String
            Get
                Return __rt_Purpose.DetailsClass.GetValue(Me, __rt_Purpose.DetailsClass.PropertySetProperties.Description)
            End Get
            Set
                __rt_Purpose.DetailsClass.SetValue(Me, __rt_Purpose.DetailsClass.PropertySetProperties.Description, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Description_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Description_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Description_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property MonitoringStations As Global.Microsoft.LightSwitch.Framework.EntityCollection(Of Global.LightSwitchApplication.MonitoringStation)
            Get
                Return __rt_Purpose.DetailsClass.GetValue(Me, __rt_Purpose.DetailsClass.PropertySetProperties.MonitoringStations)
            End Get
        End Property
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property MonitoringStationsQuery As Microsoft.LightSwitch.IDataServiceQueryable(Of Global.LightSwitchApplication.MonitoringStation)
            Get
                Return __rt_Purpose.DetailsClass.GetQuery(Me, __rt_Purpose.DetailsClass.PropertySetProperties.MonitoringStations)
            End Get
        End Property

        #End Region
    
        #Region "Details Class"
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of _
                __rt_Purpose, _
                __rt_Purpose.DetailsClass, _
                __rt_Purpose.DetailsClass.IImplementation, _
                __rt_Purpose.DetailsClass.PropertySet, _
                Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __rt_Purpose, __rt_Purpose.DetailsClass), _
                Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __rt_Purpose, __rt_Purpose.DetailsClass))
    
            Shared Sub New()
                Dim initializeEntry = __rt_Purpose.DetailsClass.PropertySetProperties.id
            End Sub
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private Shared ReadOnly __rt_PurposeEntry As Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __rt_Purpose, __rt_Purpose.DetailsClass).Entry = _
                New Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __rt_Purpose, __rt_Purpose.DetailsClass).Entry( _
                    AddressOf __rt_Purpose.DetailsClass.__rt_Purpose_CreateNew, _
                    AddressOf __rt_Purpose.DetailsClass.__rt_Purpose_Created, _
                    AddressOf __rt_Purpose.DetailsClass.__rt_Purpose_AllowSaveWithErrors)
            Private Shared Function __rt_Purpose_CreateNew(es As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __rt_Purpose)) As __rt_Purpose
                Return New __rt_Purpose(es)
            End Function
            Private Shared Sub __rt_Purpose_Created(e As __rt_Purpose)
                e.rt_Purpose_Created()
            End Sub
            Private Shared Function __rt_Purpose_AllowSaveWithErrors(e As __rt_Purpose) As Boolean
                Dim result As Boolean = False
                e.rt_Purpose_AllowSaveWithErrors(result)
                Return result
            End Function
    
            Public Sub New()
                MyBase.New()
            End Sub
    
            Public ReadOnly Shadows Property Commands As Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __rt_Purpose, __rt_Purpose.DetailsClass)
                Get
                    Return MyBase.Commands
                End Get
            End Property
    
            Public ReadOnly Shadows Property Methods As Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __rt_Purpose, __rt_Purpose.DetailsClass)
                Get
                    Return MyBase.Methods
                End Get
            End Property
    
            Public ReadOnly Shadows Property Properties As __rt_Purpose.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet(Of __rt_Purpose, __rt_Purpose.DetailsClass)
    
                Public Sub New()
                    MyBase.New()
                End Sub
    
                Public ReadOnly Property id As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __rt_Purpose, __rt_Purpose.DetailsClass, Integer)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__rt_Purpose.DetailsClass.PropertySetProperties.id),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __rt_Purpose, __rt_Purpose.DetailsClass, Integer))
                    End Get
                End Property
                
                Public ReadOnly Property Purpose As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __rt_Purpose, __rt_Purpose.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__rt_Purpose.DetailsClass.PropertySetProperties.Purpose),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __rt_Purpose, __rt_Purpose.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Description As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __rt_Purpose, __rt_Purpose.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__rt_Purpose.DetailsClass.PropertySetProperties.Description),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __rt_Purpose, __rt_Purpose.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property MonitoringStations As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __rt_Purpose, __rt_Purpose.DetailsClass, Global.LightSwitchApplication.MonitoringStation)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__rt_Purpose.DetailsClass.PropertySetProperties.MonitoringStations),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __rt_Purpose, __rt_Purpose.DetailsClass, Global.LightSwitchApplication.MonitoringStation))
                    End Get
                End Property
                
            End Class
    
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            Public Interface IImplementation
                Inherits Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
                Shadows Property id As Integer
                Shadows Property Purpose As String
                Shadows Property Description As String
                Shadows ReadOnly Property MonitoringStations As Global.System.Collections.IEnumerable
    
            End Interface
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend Class PropertySetProperties
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly id As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __rt_Purpose, __rt_Purpose.DetailsClass, Integer).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __rt_Purpose, __rt_Purpose.DetailsClass, Integer).Entry( _
                        "id", _
                        AddressOf __rt_Purpose.DetailsClass.PropertySetProperties._id_Stub, _
                        AddressOf __rt_Purpose.DetailsClass.PropertySetProperties._id_ComputeIsReadOnly, _
                        AddressOf __rt_Purpose.DetailsClass.PropertySetProperties._id_Validate, _
                        AddressOf __rt_Purpose.DetailsClass.PropertySetProperties._id_GetImplementationValue, _
                        AddressOf __rt_Purpose.DetailsClass.PropertySetProperties._id_SetImplementationValue, _
                        AddressOf __rt_Purpose.DetailsClass.PropertySetProperties._id_OnValueChanged)
                Private Shared Sub _id_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __rt_Purpose.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __rt_Purpose, __rt_Purpose.DetailsClass, Integer).Data), d As __rt_Purpose.DetailsClass, sf As Object)
                    c(d, d._id, sf)
                End Sub
                Private Shared Function _id_ComputeIsReadOnly(e As __rt_Purpose) As Boolean
                    Dim result As Boolean = False
                    e.id_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _id_Validate(e As __rt_Purpose, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.id_Validate(r)
                End Sub
                Private Shared Function _id_GetImplementationValue(d As __rt_Purpose.DetailsClass) As Integer
                    Return d.ImplementationEntity.id
                End Function
                Private Shared Sub _id_SetImplementationValue(d As __rt_Purpose.DetailsClass, v As Integer)
                    d.ImplementationEntity.id = v
                End Sub
                Private Shared Sub _id_OnValueChanged(e As __rt_Purpose)
                    e.id_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Purpose As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __rt_Purpose, __rt_Purpose.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __rt_Purpose, __rt_Purpose.DetailsClass, String).Entry( _
                        "Purpose", _
                        AddressOf __rt_Purpose.DetailsClass.PropertySetProperties._Purpose_Stub, _
                        AddressOf __rt_Purpose.DetailsClass.PropertySetProperties._Purpose_ComputeIsReadOnly, _
                        AddressOf __rt_Purpose.DetailsClass.PropertySetProperties._Purpose_Validate, _
                        AddressOf __rt_Purpose.DetailsClass.PropertySetProperties._Purpose_GetImplementationValue, _
                        AddressOf __rt_Purpose.DetailsClass.PropertySetProperties._Purpose_SetImplementationValue, _
                        AddressOf __rt_Purpose.DetailsClass.PropertySetProperties._Purpose_OnValueChanged)
                Private Shared Sub _Purpose_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __rt_Purpose.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __rt_Purpose, __rt_Purpose.DetailsClass, String).Data), d As __rt_Purpose.DetailsClass, sf As Object)
                    c(d, d._Purpose, sf)
                End Sub
                Private Shared Function _Purpose_ComputeIsReadOnly(e As __rt_Purpose) As Boolean
                    Dim result As Boolean = False
                    e.Purpose_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Purpose_Validate(e As __rt_Purpose, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Purpose_Validate(r)
                End Sub
                Private Shared Function _Purpose_GetImplementationValue(d As __rt_Purpose.DetailsClass) As String
                    Return d.ImplementationEntity.Purpose
                End Function
                Private Shared Sub _Purpose_SetImplementationValue(d As __rt_Purpose.DetailsClass, v As String)
                    d.ImplementationEntity.Purpose = v
                End Sub
                Private Shared Sub _Purpose_OnValueChanged(e As __rt_Purpose)
                    e.Purpose_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Description As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __rt_Purpose, __rt_Purpose.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __rt_Purpose, __rt_Purpose.DetailsClass, String).Entry( _
                        "Description", _
                        AddressOf __rt_Purpose.DetailsClass.PropertySetProperties._Description_Stub, _
                        AddressOf __rt_Purpose.DetailsClass.PropertySetProperties._Description_ComputeIsReadOnly, _
                        AddressOf __rt_Purpose.DetailsClass.PropertySetProperties._Description_Validate, _
                        AddressOf __rt_Purpose.DetailsClass.PropertySetProperties._Description_GetImplementationValue, _
                        AddressOf __rt_Purpose.DetailsClass.PropertySetProperties._Description_SetImplementationValue, _
                        AddressOf __rt_Purpose.DetailsClass.PropertySetProperties._Description_OnValueChanged)
                Private Shared Sub _Description_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __rt_Purpose.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __rt_Purpose, __rt_Purpose.DetailsClass, String).Data), d As __rt_Purpose.DetailsClass, sf As Object)
                    c(d, d._Description, sf)
                End Sub
                Private Shared Function _Description_ComputeIsReadOnly(e As __rt_Purpose) As Boolean
                    Dim result As Boolean = False
                    e.Description_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Description_Validate(e As __rt_Purpose, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Description_Validate(r)
                End Sub
                Private Shared Function _Description_GetImplementationValue(d As __rt_Purpose.DetailsClass) As String
                    Return d.ImplementationEntity.Description
                End Function
                Private Shared Sub _Description_SetImplementationValue(d As __rt_Purpose.DetailsClass, v As String)
                    d.ImplementationEntity.Description = v
                End Sub
                Private Shared Sub _Description_OnValueChanged(e As __rt_Purpose)
                    e.Description_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly MonitoringStations As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __rt_Purpose, __rt_Purpose.DetailsClass, Global.LightSwitchApplication.MonitoringStation).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __rt_Purpose, __rt_Purpose.DetailsClass, Global.LightSwitchApplication.MonitoringStation).Entry( _
                        "MonitoringStations", _
                        AddressOf __rt_Purpose.DetailsClass.PropertySetProperties._MonitoringStations_Stub, _
                        AddressOf __rt_Purpose.DetailsClass.PropertySetProperties._MonitoringStations_GetReferencedEntities, _
                        AddressOf __rt_Purpose.DetailsClass.PropertySetProperties._MonitoringStations_GetEntityCollection)
                Private Shared Sub _MonitoringStations_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __rt_Purpose.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __rt_Purpose, __rt_Purpose.DetailsClass, Global.LightSwitchApplication.MonitoringStation).Data), d As __rt_Purpose.DetailsClass, sf As Object)
                    c(d, d._MonitoringStations, sf)
                End Sub
                Private Shared Function _MonitoringStations_GetReferencedEntities(d As __rt_Purpose.DetailsClass) As Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.MonitoringStation)
                    Return d.GetReferencedEntities(Of Global.LightSwitchApplication.MonitoringStation, Global.LightSwitchApplication.MonitoringStation.DetailsClass)(__rt_Purpose.DetailsClass.PropertySetProperties.MonitoringStations, d._MonitoringStations)
                End Function
                Private Shared Function _MonitoringStations_GetEntityCollection(d As __rt_Purpose.DetailsClass) As Global.System.Collections.IEnumerable
                    Return d.ImplementationEntity.MonitoringStations
                End Function
    
            End Class
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _id As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __rt_Purpose, __rt_Purpose.DetailsClass, Integer).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Purpose As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __rt_Purpose, __rt_Purpose.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Description As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __rt_Purpose, __rt_Purpose.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _MonitoringStations As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __rt_Purpose, __rt_Purpose.DetailsClass, Global.LightSwitchApplication.MonitoringStation).Data
            
        End Class
    
        #End Region
    
    End Class
    
    #End Region
End Namespace
