
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports __PumpStation = LightSwitchApplication.PumpStation

Namespace LightSwitchApplication

    #Region "Entities"
    
    ''' <summary>
    ''' No Modeled Description Available
    ''' </summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
    Public NotInheritable Partial Class PumpStation
        Inherits Global.Microsoft.LightSwitch.Framework.Base.EntityObject(Of __PumpStation, __PumpStation.DetailsClass)
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Initializes a new instance of the PumpStation entity.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New()
            Me.New(Nothing)
        End Sub
    
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New(entitySet As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __PumpStation))
            MyBase.New(entitySet)
            
            __PumpStation.DetailsClass.Initialize(Me)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub PumpStation_Created()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub PumpStation_AllowSaveWithErrors(ByRef result As Boolean)
        End Sub
    
        #End Region
    
        #Region "Private Properties"
        
        ''' <summary>
        ''' Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property Application As Global.Microsoft.LightSwitch.IApplication(Of Global.LightSwitchApplication.DataWorkspace)
            Get
                Return Global.LightSwitchApplication.Application.Current
            End Get
        End Property
        
        ''' <summary>
        ''' Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property DataWorkspace As Global.LightSwitchApplication.DataWorkspace
            Get
                Return DirectCast(Me.Details.EntitySet.Details.DataService.Details.DataWorkspace, Global.LightSwitchApplication.DataWorkspace)
            End Get
        End Property
        
        #End Region
    
        #Region "Public Properties"
    
        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property ID_PS As Integer
            Get
                Return __PumpStation.DetailsClass.GetValue(Me, __PumpStation.DetailsClass.PropertySetProperties.ID_PS)
            End Get
            Set
                __PumpStation.DetailsClass.SetValue(Me, __PumpStation.DetailsClass.PropertySetProperties.ID_PS, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ID_PS_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ID_PS_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ID_PS_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property PumpStationCode As String
            Get
                Return __PumpStation.DetailsClass.GetValue(Me, __PumpStation.DetailsClass.PropertySetProperties.PumpStationCode)
            End Get
            Set
                __PumpStation.DetailsClass.SetValue(Me, __PumpStation.DetailsClass.PropertySetProperties.PumpStationCode, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub PumpStationCode_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub PumpStationCode_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub PumpStationCode_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property NumberCode As Global.System.Nullable(Of Short)
            Get
                Return __PumpStation.DetailsClass.GetValue(Me, __PumpStation.DetailsClass.PropertySetProperties.NumberCode)
            End Get
            Set
                __PumpStation.DetailsClass.SetValue(Me, __PumpStation.DetailsClass.PropertySetProperties.NumberCode, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub NumberCode_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub NumberCode_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub NumberCode_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property PumpStationType As String
            Get
                Return __PumpStation.DetailsClass.GetValue(Me, __PumpStation.DetailsClass.PropertySetProperties.PumpStationType)
            End Get
            Set
                __PumpStation.DetailsClass.SetValue(Me, __PumpStation.DetailsClass.PropertySetProperties.PumpStationType, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub PumpStationType_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub PumpStationType_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub PumpStationType_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property NumberOfPumps As Global.System.Nullable(Of Short)
            Get
                Return __PumpStation.DetailsClass.GetValue(Me, __PumpStation.DetailsClass.PropertySetProperties.NumberOfPumps)
            End Get
            Set
                __PumpStation.DetailsClass.SetValue(Me, __PumpStation.DetailsClass.PropertySetProperties.NumberOfPumps, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub NumberOfPumps_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub NumberOfPumps_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub NumberOfPumps_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property as_PumpStation_MonitoringStations As Global.Microsoft.LightSwitch.Framework.EntityCollection(Of Global.LightSwitchApplication.as_PumpStation_MonitoringStation)
            Get
                Return __PumpStation.DetailsClass.GetValue(Me, __PumpStation.DetailsClass.PropertySetProperties.as_PumpStation_MonitoringStations)
            End Get
        End Property
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property as_PumpStation_MonitoringStationsQuery As Microsoft.LightSwitch.IDataServiceQueryable(Of Global.LightSwitchApplication.as_PumpStation_MonitoringStation)
            Get
                Return __PumpStation.DetailsClass.GetQuery(Me, __PumpStation.DetailsClass.PropertySetProperties.as_PumpStation_MonitoringStations)
            End Get
        End Property

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property rt_System As Global.LightSwitchApplication.rt_System
            Get
                Return __PumpStation.DetailsClass.GetValue(Me, __PumpStation.DetailsClass.PropertySetProperties.rt_System)
            End Get
            Set
                __PumpStation.DetailsClass.SetValue(Me, __PumpStation.DetailsClass.PropertySetProperties.rt_System, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub rt_System_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub rt_System_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub rt_System_Changed()
        End Sub

        #End Region
    
        #Region "Details Class"
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of _
                __PumpStation, _
                __PumpStation.DetailsClass, _
                __PumpStation.DetailsClass.IImplementation, _
                __PumpStation.DetailsClass.PropertySet, _
                Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __PumpStation, __PumpStation.DetailsClass), _
                Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __PumpStation, __PumpStation.DetailsClass))
    
            Shared Sub New()
                Dim initializeEntry = __PumpStation.DetailsClass.PropertySetProperties.ID_PS
            End Sub
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private Shared ReadOnly __PumpStationEntry As Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __PumpStation, __PumpStation.DetailsClass).Entry = _
                New Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __PumpStation, __PumpStation.DetailsClass).Entry( _
                    AddressOf __PumpStation.DetailsClass.__PumpStation_CreateNew, _
                    AddressOf __PumpStation.DetailsClass.__PumpStation_Created, _
                    AddressOf __PumpStation.DetailsClass.__PumpStation_AllowSaveWithErrors)
            Private Shared Function __PumpStation_CreateNew(es As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __PumpStation)) As __PumpStation
                Return New __PumpStation(es)
            End Function
            Private Shared Sub __PumpStation_Created(e As __PumpStation)
                e.PumpStation_Created()
            End Sub
            Private Shared Function __PumpStation_AllowSaveWithErrors(e As __PumpStation) As Boolean
                Dim result As Boolean = False
                e.PumpStation_AllowSaveWithErrors(result)
                Return result
            End Function
    
            Public Sub New()
                MyBase.New()
            End Sub
    
            Public ReadOnly Shadows Property Commands As Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __PumpStation, __PumpStation.DetailsClass)
                Get
                    Return MyBase.Commands
                End Get
            End Property
    
            Public ReadOnly Shadows Property Methods As Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __PumpStation, __PumpStation.DetailsClass)
                Get
                    Return MyBase.Methods
                End Get
            End Property
    
            Public ReadOnly Shadows Property Properties As __PumpStation.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet(Of __PumpStation, __PumpStation.DetailsClass)
    
                Public Sub New()
                    MyBase.New()
                End Sub
    
                Public ReadOnly Property ID_PS As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PumpStation, __PumpStation.DetailsClass, Integer)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__PumpStation.DetailsClass.PropertySetProperties.ID_PS),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PumpStation, __PumpStation.DetailsClass, Integer))
                    End Get
                End Property
                
                Public ReadOnly Property PumpStationCode As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PumpStation, __PumpStation.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__PumpStation.DetailsClass.PropertySetProperties.PumpStationCode),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PumpStation, __PumpStation.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property NumberCode As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PumpStation, __PumpStation.DetailsClass, Global.System.Nullable(Of Short))
                    Get
                        Return TryCast(
                            MyBase.GetItem(__PumpStation.DetailsClass.PropertySetProperties.NumberCode),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PumpStation, __PumpStation.DetailsClass, Global.System.Nullable(Of Short)))
                    End Get
                End Property
                
                Public ReadOnly Property PumpStationType As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PumpStation, __PumpStation.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__PumpStation.DetailsClass.PropertySetProperties.PumpStationType),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PumpStation, __PumpStation.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property NumberOfPumps As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PumpStation, __PumpStation.DetailsClass, Global.System.Nullable(Of Short))
                    Get
                        Return TryCast(
                            MyBase.GetItem(__PumpStation.DetailsClass.PropertySetProperties.NumberOfPumps),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PumpStation, __PumpStation.DetailsClass, Global.System.Nullable(Of Short)))
                    End Get
                End Property
                
                Public ReadOnly Property as_PumpStation_MonitoringStations As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __PumpStation, __PumpStation.DetailsClass, Global.LightSwitchApplication.as_PumpStation_MonitoringStation)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__PumpStation.DetailsClass.PropertySetProperties.as_PumpStation_MonitoringStations),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __PumpStation, __PumpStation.DetailsClass, Global.LightSwitchApplication.as_PumpStation_MonitoringStation))
                    End Get
                End Property
                
                Public ReadOnly Property rt_System As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __PumpStation, __PumpStation.DetailsClass, Global.LightSwitchApplication.rt_System)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__PumpStation.DetailsClass.PropertySetProperties.rt_System),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __PumpStation, __PumpStation.DetailsClass, Global.LightSwitchApplication.rt_System))
                    End Get
                End Property
                
            End Class
    
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            Public Interface IImplementation
                Inherits Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
                Shadows Property ID_PS As Integer
                Shadows Property PumpStationCode As String
                Shadows Property NumberCode As Global.System.Nullable(Of Short)
                Shadows Property PumpStationType As String
                Shadows Property NumberOfPumps As Global.System.Nullable(Of Short)
                Shadows ReadOnly Property as_PumpStation_MonitoringStations As Global.System.Collections.IEnumerable
                Shadows Property rt_System As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
            End Interface
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend Class PropertySetProperties
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly ID_PS As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PumpStation, __PumpStation.DetailsClass, Integer).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PumpStation, __PumpStation.DetailsClass, Integer).Entry( _
                        "ID_PS", _
                        AddressOf __PumpStation.DetailsClass.PropertySetProperties._ID_PS_Stub, _
                        AddressOf __PumpStation.DetailsClass.PropertySetProperties._ID_PS_ComputeIsReadOnly, _
                        AddressOf __PumpStation.DetailsClass.PropertySetProperties._ID_PS_Validate, _
                        AddressOf __PumpStation.DetailsClass.PropertySetProperties._ID_PS_GetImplementationValue, _
                        AddressOf __PumpStation.DetailsClass.PropertySetProperties._ID_PS_SetImplementationValue, _
                        AddressOf __PumpStation.DetailsClass.PropertySetProperties._ID_PS_OnValueChanged)
                Private Shared Sub _ID_PS_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __PumpStation.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PumpStation, __PumpStation.DetailsClass, Integer).Data), d As __PumpStation.DetailsClass, sf As Object)
                    c(d, d._ID_PS, sf)
                End Sub
                Private Shared Function _ID_PS_ComputeIsReadOnly(e As __PumpStation) As Boolean
                    Dim result As Boolean = False
                    e.ID_PS_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _ID_PS_Validate(e As __PumpStation, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.ID_PS_Validate(r)
                End Sub
                Private Shared Function _ID_PS_GetImplementationValue(d As __PumpStation.DetailsClass) As Integer
                    Return d.ImplementationEntity.ID_PS
                End Function
                Private Shared Sub _ID_PS_SetImplementationValue(d As __PumpStation.DetailsClass, v As Integer)
                    d.ImplementationEntity.ID_PS = v
                End Sub
                Private Shared Sub _ID_PS_OnValueChanged(e As __PumpStation)
                    e.ID_PS_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly PumpStationCode As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PumpStation, __PumpStation.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PumpStation, __PumpStation.DetailsClass, String).Entry( _
                        "PumpStationCode", _
                        AddressOf __PumpStation.DetailsClass.PropertySetProperties._PumpStationCode_Stub, _
                        AddressOf __PumpStation.DetailsClass.PropertySetProperties._PumpStationCode_ComputeIsReadOnly, _
                        AddressOf __PumpStation.DetailsClass.PropertySetProperties._PumpStationCode_Validate, _
                        AddressOf __PumpStation.DetailsClass.PropertySetProperties._PumpStationCode_GetImplementationValue, _
                        AddressOf __PumpStation.DetailsClass.PropertySetProperties._PumpStationCode_SetImplementationValue, _
                        AddressOf __PumpStation.DetailsClass.PropertySetProperties._PumpStationCode_OnValueChanged)
                Private Shared Sub _PumpStationCode_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __PumpStation.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PumpStation, __PumpStation.DetailsClass, String).Data), d As __PumpStation.DetailsClass, sf As Object)
                    c(d, d._PumpStationCode, sf)
                End Sub
                Private Shared Function _PumpStationCode_ComputeIsReadOnly(e As __PumpStation) As Boolean
                    Dim result As Boolean = False
                    e.PumpStationCode_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _PumpStationCode_Validate(e As __PumpStation, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.PumpStationCode_Validate(r)
                End Sub
                Private Shared Function _PumpStationCode_GetImplementationValue(d As __PumpStation.DetailsClass) As String
                    Return d.ImplementationEntity.PumpStationCode
                End Function
                Private Shared Sub _PumpStationCode_SetImplementationValue(d As __PumpStation.DetailsClass, v As String)
                    d.ImplementationEntity.PumpStationCode = v
                End Sub
                Private Shared Sub _PumpStationCode_OnValueChanged(e As __PumpStation)
                    e.PumpStationCode_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly NumberCode As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PumpStation, __PumpStation.DetailsClass, Global.System.Nullable(Of Short)).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PumpStation, __PumpStation.DetailsClass, Global.System.Nullable(Of Short)).Entry( _
                        "NumberCode", _
                        AddressOf __PumpStation.DetailsClass.PropertySetProperties._NumberCode_Stub, _
                        AddressOf __PumpStation.DetailsClass.PropertySetProperties._NumberCode_ComputeIsReadOnly, _
                        AddressOf __PumpStation.DetailsClass.PropertySetProperties._NumberCode_Validate, _
                        AddressOf __PumpStation.DetailsClass.PropertySetProperties._NumberCode_GetImplementationValue, _
                        AddressOf __PumpStation.DetailsClass.PropertySetProperties._NumberCode_SetImplementationValue, _
                        AddressOf __PumpStation.DetailsClass.PropertySetProperties._NumberCode_OnValueChanged)
                Private Shared Sub _NumberCode_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __PumpStation.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PumpStation, __PumpStation.DetailsClass, Global.System.Nullable(Of Short)).Data), d As __PumpStation.DetailsClass, sf As Object)
                    c(d, d._NumberCode, sf)
                End Sub
                Private Shared Function _NumberCode_ComputeIsReadOnly(e As __PumpStation) As Boolean
                    Dim result As Boolean = False
                    e.NumberCode_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _NumberCode_Validate(e As __PumpStation, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.NumberCode_Validate(r)
                End Sub
                Private Shared Function _NumberCode_GetImplementationValue(d As __PumpStation.DetailsClass) As Global.System.Nullable(Of Short)
                    Return d.ImplementationEntity.NumberCode
                End Function
                Private Shared Sub _NumberCode_SetImplementationValue(d As __PumpStation.DetailsClass, v As Global.System.Nullable(Of Short))
                    d.ImplementationEntity.NumberCode = v
                End Sub
                Private Shared Sub _NumberCode_OnValueChanged(e As __PumpStation)
                    e.NumberCode_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly PumpStationType As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PumpStation, __PumpStation.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PumpStation, __PumpStation.DetailsClass, String).Entry( _
                        "PumpStationType", _
                        AddressOf __PumpStation.DetailsClass.PropertySetProperties._PumpStationType_Stub, _
                        AddressOf __PumpStation.DetailsClass.PropertySetProperties._PumpStationType_ComputeIsReadOnly, _
                        AddressOf __PumpStation.DetailsClass.PropertySetProperties._PumpStationType_Validate, _
                        AddressOf __PumpStation.DetailsClass.PropertySetProperties._PumpStationType_GetImplementationValue, _
                        AddressOf __PumpStation.DetailsClass.PropertySetProperties._PumpStationType_SetImplementationValue, _
                        AddressOf __PumpStation.DetailsClass.PropertySetProperties._PumpStationType_OnValueChanged)
                Private Shared Sub _PumpStationType_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __PumpStation.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PumpStation, __PumpStation.DetailsClass, String).Data), d As __PumpStation.DetailsClass, sf As Object)
                    c(d, d._PumpStationType, sf)
                End Sub
                Private Shared Function _PumpStationType_ComputeIsReadOnly(e As __PumpStation) As Boolean
                    Dim result As Boolean = False
                    e.PumpStationType_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _PumpStationType_Validate(e As __PumpStation, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.PumpStationType_Validate(r)
                End Sub
                Private Shared Function _PumpStationType_GetImplementationValue(d As __PumpStation.DetailsClass) As String
                    Return d.ImplementationEntity.PumpStationType
                End Function
                Private Shared Sub _PumpStationType_SetImplementationValue(d As __PumpStation.DetailsClass, v As String)
                    d.ImplementationEntity.PumpStationType = v
                End Sub
                Private Shared Sub _PumpStationType_OnValueChanged(e As __PumpStation)
                    e.PumpStationType_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly NumberOfPumps As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PumpStation, __PumpStation.DetailsClass, Global.System.Nullable(Of Short)).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PumpStation, __PumpStation.DetailsClass, Global.System.Nullable(Of Short)).Entry( _
                        "NumberOfPumps", _
                        AddressOf __PumpStation.DetailsClass.PropertySetProperties._NumberOfPumps_Stub, _
                        AddressOf __PumpStation.DetailsClass.PropertySetProperties._NumberOfPumps_ComputeIsReadOnly, _
                        AddressOf __PumpStation.DetailsClass.PropertySetProperties._NumberOfPumps_Validate, _
                        AddressOf __PumpStation.DetailsClass.PropertySetProperties._NumberOfPumps_GetImplementationValue, _
                        AddressOf __PumpStation.DetailsClass.PropertySetProperties._NumberOfPumps_SetImplementationValue, _
                        AddressOf __PumpStation.DetailsClass.PropertySetProperties._NumberOfPumps_OnValueChanged)
                Private Shared Sub _NumberOfPumps_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __PumpStation.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PumpStation, __PumpStation.DetailsClass, Global.System.Nullable(Of Short)).Data), d As __PumpStation.DetailsClass, sf As Object)
                    c(d, d._NumberOfPumps, sf)
                End Sub
                Private Shared Function _NumberOfPumps_ComputeIsReadOnly(e As __PumpStation) As Boolean
                    Dim result As Boolean = False
                    e.NumberOfPumps_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _NumberOfPumps_Validate(e As __PumpStation, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.NumberOfPumps_Validate(r)
                End Sub
                Private Shared Function _NumberOfPumps_GetImplementationValue(d As __PumpStation.DetailsClass) As Global.System.Nullable(Of Short)
                    Return d.ImplementationEntity.NumberOfPumps
                End Function
                Private Shared Sub _NumberOfPumps_SetImplementationValue(d As __PumpStation.DetailsClass, v As Global.System.Nullable(Of Short))
                    d.ImplementationEntity.NumberOfPumps = v
                End Sub
                Private Shared Sub _NumberOfPumps_OnValueChanged(e As __PumpStation)
                    e.NumberOfPumps_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly as_PumpStation_MonitoringStations As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __PumpStation, __PumpStation.DetailsClass, Global.LightSwitchApplication.as_PumpStation_MonitoringStation).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __PumpStation, __PumpStation.DetailsClass, Global.LightSwitchApplication.as_PumpStation_MonitoringStation).Entry( _
                        "as_PumpStation_MonitoringStations", _
                        AddressOf __PumpStation.DetailsClass.PropertySetProperties._as_PumpStation_MonitoringStations_Stub, _
                        AddressOf __PumpStation.DetailsClass.PropertySetProperties._as_PumpStation_MonitoringStations_GetReferencedEntities, _
                        AddressOf __PumpStation.DetailsClass.PropertySetProperties._as_PumpStation_MonitoringStations_GetEntityCollection)
                Private Shared Sub _as_PumpStation_MonitoringStations_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __PumpStation.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __PumpStation, __PumpStation.DetailsClass, Global.LightSwitchApplication.as_PumpStation_MonitoringStation).Data), d As __PumpStation.DetailsClass, sf As Object)
                    c(d, d._as_PumpStation_MonitoringStations, sf)
                End Sub
                Private Shared Function _as_PumpStation_MonitoringStations_GetReferencedEntities(d As __PumpStation.DetailsClass) As Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.as_PumpStation_MonitoringStation)
                    Return d.GetReferencedEntities(Of Global.LightSwitchApplication.as_PumpStation_MonitoringStation, Global.LightSwitchApplication.as_PumpStation_MonitoringStation.DetailsClass)(__PumpStation.DetailsClass.PropertySetProperties.as_PumpStation_MonitoringStations, d._as_PumpStation_MonitoringStations)
                End Function
                Private Shared Function _as_PumpStation_MonitoringStations_GetEntityCollection(d As __PumpStation.DetailsClass) As Global.System.Collections.IEnumerable
                    Return d.ImplementationEntity.as_PumpStation_MonitoringStations
                End Function
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly rt_System As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __PumpStation, __PumpStation.DetailsClass, Global.LightSwitchApplication.rt_System).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __PumpStation, __PumpStation.DetailsClass, Global.LightSwitchApplication.rt_System).Entry( _
                        "rt_System", _
                        AddressOf __PumpStation.DetailsClass.PropertySetProperties._rt_System_Stub, _
                        AddressOf __PumpStation.DetailsClass.PropertySetProperties._rt_System_ComputeIsReadOnly, _
                        AddressOf __PumpStation.DetailsClass.PropertySetProperties._rt_System_Validate, _
                        AddressOf __PumpStation.DetailsClass.PropertySetProperties._rt_System_GetCoreImplementationValue, _
                        AddressOf __PumpStation.DetailsClass.PropertySetProperties._rt_System_GetImplementationValue, _
                        AddressOf __PumpStation.DetailsClass.PropertySetProperties._rt_System_SetImplementationValue, _
                        AddressOf __PumpStation.DetailsClass.PropertySetProperties._rt_System_Refresh, _
                        AddressOf __PumpStation.DetailsClass.PropertySetProperties._rt_System_OnValueChanged)
                Private Shared Sub _rt_System_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __PumpStation.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __PumpStation, __PumpStation.DetailsClass, Global.LightSwitchApplication.rt_System).Data), d As __PumpStation.DetailsClass, sf As Object)
                    c(d, d._rt_System, sf)
                End Sub
                Private Shared Function _rt_System_ComputeIsReadOnly(e As __PumpStation) As Boolean
                    Dim result As Boolean = False
                    e.rt_System_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _rt_System_Validate(e As __PumpStation, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.rt_System_Validate(r)
                End Sub
                Private Shared Function _rt_System_GetCoreImplementationValue(d as __PumpStation.DetailsClass) As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
                    Return d.ImplementationEntity.rt_System
                End Function
                Private Shared Function _rt_System_GetImplementationValue(d as __PumpStation.DetailsClass) As Global.LightSwitchApplication.rt_System
                    Return d.GetImplementationValue(Of Global.LightSwitchApplication.rt_System, Global.LightSwitchApplication.rt_System.DetailsClass)(__PumpStation.DetailsClass.PropertySetProperties.rt_System, d._rt_System)
                End Function
                Private Shared Sub _rt_System_SetImplementationValue(d As __PumpStation.DetailsClass, v As Global.LightSwitchApplication.rt_System)
                    d.SetImplementationValue(__PumpStation.DetailsClass.PropertySetProperties.rt_System, d._rt_System, Sub(i, ev) i.rt_System = ev, v)
                End Sub
                Private Shared Sub _rt_System_Refresh(d As __PumpStation.DetailsClass)
                    d.RefreshNavigationProperty(__PumpStation.DetailsClass.PropertySetProperties.rt_System, d._rt_System)
                End Sub
                Private Shared Sub _rt_System_OnValueChanged(e As __PumpStation)
                    e.rt_System_Changed()
                End Sub
    
            End Class
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _ID_PS As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PumpStation, __PumpStation.DetailsClass, Integer).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _PumpStationCode As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PumpStation, __PumpStation.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _NumberCode As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PumpStation, __PumpStation.DetailsClass, Global.System.Nullable(Of Short)).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _PumpStationType As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PumpStation, __PumpStation.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _NumberOfPumps As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PumpStation, __PumpStation.DetailsClass, Global.System.Nullable(Of Short)).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _as_PumpStation_MonitoringStations As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __PumpStation, __PumpStation.DetailsClass, Global.LightSwitchApplication.as_PumpStation_MonitoringStation).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _rt_System As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __PumpStation, __PumpStation.DetailsClass, Global.LightSwitchApplication.rt_System).Data
            
        End Class
    
        #End Region
    
    End Class
    
    #End Region
End Namespace
