
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports __ProjectAndProgram = LightSwitchApplication.ProjectAndProgram

Namespace LightSwitchApplication

    #Region "Entities"
    
    ''' <summary>
    ''' No Modeled Description Available
    ''' </summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
    Public NotInheritable Partial Class ProjectAndProgram
        Inherits Global.Microsoft.LightSwitch.Framework.Base.EntityObject(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass)
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Initializes a new instance of the ProjectAndProgram entity.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New()
            Me.New(Nothing)
        End Sub
    
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New(entitySet As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __ProjectAndProgram))
            MyBase.New(entitySet)
            
            __ProjectAndProgram.DetailsClass.Initialize(Me)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ProjectAndProgram_Created()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ProjectAndProgram_AllowSaveWithErrors(ByRef result As Boolean)
        End Sub
    
        #End Region
    
        #Region "Private Properties"
        
        ''' <summary>
        ''' Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property Application As Global.Microsoft.LightSwitch.IApplication(Of Global.LightSwitchApplication.DataWorkspace)
            Get
                Return Global.LightSwitchApplication.Application.Current
            End Get
        End Property
        
        ''' <summary>
        ''' Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property DataWorkspace As Global.LightSwitchApplication.DataWorkspace
            Get
                Return DirectCast(Me.Details.EntitySet.Details.DataService.Details.DataWorkspace, Global.LightSwitchApplication.DataWorkspace)
            End Get
        End Property
        
        #End Region
    
        #Region "Public Properties"
    
        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property ID As Integer
            Get
                Return __ProjectAndProgram.DetailsClass.GetValue(Me, __ProjectAndProgram.DetailsClass.PropertySetProperties.ID)
            End Get
            Set
                __ProjectAndProgram.DetailsClass.SetValue(Me, __ProjectAndProgram.DetailsClass.PropertySetProperties.ID, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ID_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ID_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ID_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property ProjectOrProgram_ID As String
            Get
                Return __ProjectAndProgram.DetailsClass.GetValue(Me, __ProjectAndProgram.DetailsClass.PropertySetProperties.ProjectOrProgram_ID)
            End Get
            Set
                __ProjectAndProgram.DetailsClass.SetValue(Me, __ProjectAndProgram.DetailsClass.PropertySetProperties.ProjectOrProgram_ID, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ProjectOrProgram_ID_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ProjectOrProgram_ID_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ProjectOrProgram_ID_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property CommonName As String
            Get
                Return __ProjectAndProgram.DetailsClass.GetValue(Me, __ProjectAndProgram.DetailsClass.PropertySetProperties.CommonName)
            End Get
            Set
                __ProjectAndProgram.DetailsClass.SetValue(Me, __ProjectAndProgram.DetailsClass.PropertySetProperties.CommonName, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CommonName_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CommonName_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CommonName_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property ADSName As String
            Get
                Return __ProjectAndProgram.DetailsClass.GetValue(Me, __ProjectAndProgram.DetailsClass.PropertySetProperties.ADSName)
            End Get
            Set
                __ProjectAndProgram.DetailsClass.SetValue(Me, __ProjectAndProgram.DetailsClass.PropertySetProperties.ADSName, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ADSName_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ADSName_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ADSName_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property ProgTypeID As Global.System.Nullable(Of Integer)
            Get
                Return __ProjectAndProgram.DetailsClass.GetValue(Me, __ProjectAndProgram.DetailsClass.PropertySetProperties.ProgTypeID)
            End Get
            Set
                __ProjectAndProgram.DetailsClass.SetValue(Me, __ProjectAndProgram.DetailsClass.PropertySetProperties.ProgTypeID, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ProgTypeID_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ProgTypeID_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ProgTypeID_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property as_Project_MonitoringStations As Global.Microsoft.LightSwitch.Framework.EntityCollection(Of Global.LightSwitchApplication.as_Project_MonitoringStation)
            Get
                Return __ProjectAndProgram.DetailsClass.GetValue(Me, __ProjectAndProgram.DetailsClass.PropertySetProperties.as_Project_MonitoringStations)
            End Get
        End Property
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property as_Project_MonitoringStationsQuery As Microsoft.LightSwitch.IDataServiceQueryable(Of Global.LightSwitchApplication.as_Project_MonitoringStation)
            Get
                Return __ProjectAndProgram.DetailsClass.GetQuery(Me, __ProjectAndProgram.DetailsClass.PropertySetProperties.as_Project_MonitoringStations)
            End Get
        End Property

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Person As Global.LightSwitchApplication.Person
            Get
                Return __ProjectAndProgram.DetailsClass.GetValue(Me, __ProjectAndProgram.DetailsClass.PropertySetProperties.Person)
            End Get
            Set
                __ProjectAndProgram.DetailsClass.SetValue(Me, __ProjectAndProgram.DetailsClass.PropertySetProperties.Person, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Person_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Person_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Person_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Person1 As Global.LightSwitchApplication.Person
            Get
                Return __ProjectAndProgram.DetailsClass.GetValue(Me, __ProjectAndProgram.DetailsClass.PropertySetProperties.Person1)
            End Get
            Set
                __ProjectAndProgram.DetailsClass.SetValue(Me, __ProjectAndProgram.DetailsClass.PropertySetProperties.Person1, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Person1_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Person1_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Person1_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property WorkGroup As Global.LightSwitchApplication.WorkGroup
            Get
                Return __ProjectAndProgram.DetailsClass.GetValue(Me, __ProjectAndProgram.DetailsClass.PropertySetProperties.WorkGroup)
            End Get
            Set
                __ProjectAndProgram.DetailsClass.SetValue(Me, __ProjectAndProgram.DetailsClass.PropertySetProperties.WorkGroup, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub WorkGroup_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub WorkGroup_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub WorkGroup_Changed()
        End Sub

        #End Region
    
        #Region "Details Class"
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of _
                __ProjectAndProgram, _
                __ProjectAndProgram.DetailsClass, _
                __ProjectAndProgram.DetailsClass.IImplementation, _
                __ProjectAndProgram.DetailsClass.PropertySet, _
                Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass), _
                Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass))
    
            Shared Sub New()
                Dim initializeEntry = __ProjectAndProgram.DetailsClass.PropertySetProperties.ID
            End Sub
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private Shared ReadOnly __ProjectAndProgramEntry As Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass).Entry = _
                New Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass).Entry( _
                    AddressOf __ProjectAndProgram.DetailsClass.__ProjectAndProgram_CreateNew, _
                    AddressOf __ProjectAndProgram.DetailsClass.__ProjectAndProgram_Created, _
                    AddressOf __ProjectAndProgram.DetailsClass.__ProjectAndProgram_AllowSaveWithErrors)
            Private Shared Function __ProjectAndProgram_CreateNew(es As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __ProjectAndProgram)) As __ProjectAndProgram
                Return New __ProjectAndProgram(es)
            End Function
            Private Shared Sub __ProjectAndProgram_Created(e As __ProjectAndProgram)
                e.ProjectAndProgram_Created()
            End Sub
            Private Shared Function __ProjectAndProgram_AllowSaveWithErrors(e As __ProjectAndProgram) As Boolean
                Dim result As Boolean = False
                e.ProjectAndProgram_AllowSaveWithErrors(result)
                Return result
            End Function
    
            Public Sub New()
                MyBase.New()
            End Sub
    
            Public ReadOnly Shadows Property Commands As Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass)
                Get
                    Return MyBase.Commands
                End Get
            End Property
    
            Public ReadOnly Shadows Property Methods As Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass)
                Get
                    Return MyBase.Methods
                End Get
            End Property
    
            Public ReadOnly Shadows Property Properties As __ProjectAndProgram.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass)
    
                Public Sub New()
                    MyBase.New()
                End Sub
    
                Public ReadOnly Property ID As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, Integer)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__ProjectAndProgram.DetailsClass.PropertySetProperties.ID),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, Integer))
                    End Get
                End Property
                
                Public ReadOnly Property ProjectOrProgram_ID As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__ProjectAndProgram.DetailsClass.PropertySetProperties.ProjectOrProgram_ID),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property CommonName As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__ProjectAndProgram.DetailsClass.PropertySetProperties.CommonName),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property ADSName As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__ProjectAndProgram.DetailsClass.PropertySetProperties.ADSName),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property ProgTypeID As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, Global.System.Nullable(Of Integer))
                    Get
                        Return TryCast(
                            MyBase.GetItem(__ProjectAndProgram.DetailsClass.PropertySetProperties.ProgTypeID),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, Global.System.Nullable(Of Integer)))
                    End Get
                End Property
                
                Public ReadOnly Property as_Project_MonitoringStations As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, Global.LightSwitchApplication.as_Project_MonitoringStation)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__ProjectAndProgram.DetailsClass.PropertySetProperties.as_Project_MonitoringStations),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, Global.LightSwitchApplication.as_Project_MonitoringStation))
                    End Get
                End Property
                
                Public ReadOnly Property Person As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, Global.LightSwitchApplication.Person)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__ProjectAndProgram.DetailsClass.PropertySetProperties.Person),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, Global.LightSwitchApplication.Person))
                    End Get
                End Property
                
                Public ReadOnly Property Person1 As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, Global.LightSwitchApplication.Person)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__ProjectAndProgram.DetailsClass.PropertySetProperties.Person1),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, Global.LightSwitchApplication.Person))
                    End Get
                End Property
                
                Public ReadOnly Property WorkGroup As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, Global.LightSwitchApplication.WorkGroup)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__ProjectAndProgram.DetailsClass.PropertySetProperties.WorkGroup),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, Global.LightSwitchApplication.WorkGroup))
                    End Get
                End Property
                
            End Class
    
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            Public Interface IImplementation
                Inherits Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
                Shadows Property ID As Integer
                Shadows Property ProjectOrProgram_ID As String
                Shadows Property CommonName As String
                Shadows Property ADSName As String
                Shadows Property ProgTypeID As Global.System.Nullable(Of Integer)
                Shadows ReadOnly Property as_Project_MonitoringStations As Global.System.Collections.IEnumerable
                Shadows Property Person As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
                Shadows Property Person1 As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
                Shadows Property WorkGroup As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
            End Interface
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend Class PropertySetProperties
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly ID As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, Integer).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, Integer).Entry( _
                        "ID", _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._ID_Stub, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._ID_ComputeIsReadOnly, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._ID_Validate, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._ID_GetImplementationValue, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._ID_SetImplementationValue, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._ID_OnValueChanged)
                Private Shared Sub _ID_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __ProjectAndProgram.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, Integer).Data), d As __ProjectAndProgram.DetailsClass, sf As Object)
                    c(d, d._ID, sf)
                End Sub
                Private Shared Function _ID_ComputeIsReadOnly(e As __ProjectAndProgram) As Boolean
                    Dim result As Boolean = False
                    e.ID_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _ID_Validate(e As __ProjectAndProgram, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.ID_Validate(r)
                End Sub
                Private Shared Function _ID_GetImplementationValue(d As __ProjectAndProgram.DetailsClass) As Integer
                    Return d.ImplementationEntity.ID
                End Function
                Private Shared Sub _ID_SetImplementationValue(d As __ProjectAndProgram.DetailsClass, v As Integer)
                    d.ImplementationEntity.ID = v
                End Sub
                Private Shared Sub _ID_OnValueChanged(e As __ProjectAndProgram)
                    e.ID_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly ProjectOrProgram_ID As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, String).Entry( _
                        "ProjectOrProgram_ID", _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._ProjectOrProgram_ID_Stub, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._ProjectOrProgram_ID_ComputeIsReadOnly, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._ProjectOrProgram_ID_Validate, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._ProjectOrProgram_ID_GetImplementationValue, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._ProjectOrProgram_ID_SetImplementationValue, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._ProjectOrProgram_ID_OnValueChanged)
                Private Shared Sub _ProjectOrProgram_ID_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __ProjectAndProgram.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, String).Data), d As __ProjectAndProgram.DetailsClass, sf As Object)
                    c(d, d._ProjectOrProgram_ID, sf)
                End Sub
                Private Shared Function _ProjectOrProgram_ID_ComputeIsReadOnly(e As __ProjectAndProgram) As Boolean
                    Dim result As Boolean = False
                    e.ProjectOrProgram_ID_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _ProjectOrProgram_ID_Validate(e As __ProjectAndProgram, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.ProjectOrProgram_ID_Validate(r)
                End Sub
                Private Shared Function _ProjectOrProgram_ID_GetImplementationValue(d As __ProjectAndProgram.DetailsClass) As String
                    Return d.ImplementationEntity.ProjectOrProgram_ID
                End Function
                Private Shared Sub _ProjectOrProgram_ID_SetImplementationValue(d As __ProjectAndProgram.DetailsClass, v As String)
                    d.ImplementationEntity.ProjectOrProgram_ID = v
                End Sub
                Private Shared Sub _ProjectOrProgram_ID_OnValueChanged(e As __ProjectAndProgram)
                    e.ProjectOrProgram_ID_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly CommonName As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, String).Entry( _
                        "CommonName", _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._CommonName_Stub, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._CommonName_ComputeIsReadOnly, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._CommonName_Validate, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._CommonName_GetImplementationValue, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._CommonName_SetImplementationValue, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._CommonName_OnValueChanged)
                Private Shared Sub _CommonName_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __ProjectAndProgram.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, String).Data), d As __ProjectAndProgram.DetailsClass, sf As Object)
                    c(d, d._CommonName, sf)
                End Sub
                Private Shared Function _CommonName_ComputeIsReadOnly(e As __ProjectAndProgram) As Boolean
                    Dim result As Boolean = False
                    e.CommonName_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _CommonName_Validate(e As __ProjectAndProgram, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.CommonName_Validate(r)
                End Sub
                Private Shared Function _CommonName_GetImplementationValue(d As __ProjectAndProgram.DetailsClass) As String
                    Return d.ImplementationEntity.CommonName
                End Function
                Private Shared Sub _CommonName_SetImplementationValue(d As __ProjectAndProgram.DetailsClass, v As String)
                    d.ImplementationEntity.CommonName = v
                End Sub
                Private Shared Sub _CommonName_OnValueChanged(e As __ProjectAndProgram)
                    e.CommonName_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly ADSName As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, String).Entry( _
                        "ADSName", _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._ADSName_Stub, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._ADSName_ComputeIsReadOnly, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._ADSName_Validate, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._ADSName_GetImplementationValue, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._ADSName_SetImplementationValue, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._ADSName_OnValueChanged)
                Private Shared Sub _ADSName_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __ProjectAndProgram.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, String).Data), d As __ProjectAndProgram.DetailsClass, sf As Object)
                    c(d, d._ADSName, sf)
                End Sub
                Private Shared Function _ADSName_ComputeIsReadOnly(e As __ProjectAndProgram) As Boolean
                    Dim result As Boolean = False
                    e.ADSName_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _ADSName_Validate(e As __ProjectAndProgram, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.ADSName_Validate(r)
                End Sub
                Private Shared Function _ADSName_GetImplementationValue(d As __ProjectAndProgram.DetailsClass) As String
                    Return d.ImplementationEntity.ADSName
                End Function
                Private Shared Sub _ADSName_SetImplementationValue(d As __ProjectAndProgram.DetailsClass, v As String)
                    d.ImplementationEntity.ADSName = v
                End Sub
                Private Shared Sub _ADSName_OnValueChanged(e As __ProjectAndProgram)
                    e.ADSName_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly ProgTypeID As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, Global.System.Nullable(Of Integer)).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, Global.System.Nullable(Of Integer)).Entry( _
                        "ProgTypeID", _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._ProgTypeID_Stub, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._ProgTypeID_ComputeIsReadOnly, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._ProgTypeID_Validate, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._ProgTypeID_GetImplementationValue, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._ProgTypeID_SetImplementationValue, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._ProgTypeID_OnValueChanged)
                Private Shared Sub _ProgTypeID_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __ProjectAndProgram.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, Global.System.Nullable(Of Integer)).Data), d As __ProjectAndProgram.DetailsClass, sf As Object)
                    c(d, d._ProgTypeID, sf)
                End Sub
                Private Shared Function _ProgTypeID_ComputeIsReadOnly(e As __ProjectAndProgram) As Boolean
                    Dim result As Boolean = False
                    e.ProgTypeID_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _ProgTypeID_Validate(e As __ProjectAndProgram, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.ProgTypeID_Validate(r)
                End Sub
                Private Shared Function _ProgTypeID_GetImplementationValue(d As __ProjectAndProgram.DetailsClass) As Global.System.Nullable(Of Integer)
                    Return d.ImplementationEntity.ProgTypeID
                End Function
                Private Shared Sub _ProgTypeID_SetImplementationValue(d As __ProjectAndProgram.DetailsClass, v As Global.System.Nullable(Of Integer))
                    d.ImplementationEntity.ProgTypeID = v
                End Sub
                Private Shared Sub _ProgTypeID_OnValueChanged(e As __ProjectAndProgram)
                    e.ProgTypeID_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly as_Project_MonitoringStations As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, Global.LightSwitchApplication.as_Project_MonitoringStation).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, Global.LightSwitchApplication.as_Project_MonitoringStation).Entry( _
                        "as_Project_MonitoringStations", _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._as_Project_MonitoringStations_Stub, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._as_Project_MonitoringStations_GetReferencedEntities, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._as_Project_MonitoringStations_GetEntityCollection)
                Private Shared Sub _as_Project_MonitoringStations_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __ProjectAndProgram.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, Global.LightSwitchApplication.as_Project_MonitoringStation).Data), d As __ProjectAndProgram.DetailsClass, sf As Object)
                    c(d, d._as_Project_MonitoringStations, sf)
                End Sub
                Private Shared Function _as_Project_MonitoringStations_GetReferencedEntities(d As __ProjectAndProgram.DetailsClass) As Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.as_Project_MonitoringStation)
                    Return d.GetReferencedEntities(Of Global.LightSwitchApplication.as_Project_MonitoringStation, Global.LightSwitchApplication.as_Project_MonitoringStation.DetailsClass)(__ProjectAndProgram.DetailsClass.PropertySetProperties.as_Project_MonitoringStations, d._as_Project_MonitoringStations)
                End Function
                Private Shared Function _as_Project_MonitoringStations_GetEntityCollection(d As __ProjectAndProgram.DetailsClass) As Global.System.Collections.IEnumerable
                    Return d.ImplementationEntity.as_Project_MonitoringStations
                End Function
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Person As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, Global.LightSwitchApplication.Person).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, Global.LightSwitchApplication.Person).Entry( _
                        "Person", _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._Person_Stub, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._Person_ComputeIsReadOnly, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._Person_Validate, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._Person_GetCoreImplementationValue, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._Person_GetImplementationValue, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._Person_SetImplementationValue, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._Person_Refresh, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._Person_OnValueChanged)
                Private Shared Sub _Person_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __ProjectAndProgram.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, Global.LightSwitchApplication.Person).Data), d As __ProjectAndProgram.DetailsClass, sf As Object)
                    c(d, d._Person, sf)
                End Sub
                Private Shared Function _Person_ComputeIsReadOnly(e As __ProjectAndProgram) As Boolean
                    Dim result As Boolean = False
                    e.Person_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Person_Validate(e As __ProjectAndProgram, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Person_Validate(r)
                End Sub
                Private Shared Function _Person_GetCoreImplementationValue(d as __ProjectAndProgram.DetailsClass) As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
                    Return d.ImplementationEntity.Person
                End Function
                Private Shared Function _Person_GetImplementationValue(d as __ProjectAndProgram.DetailsClass) As Global.LightSwitchApplication.Person
                    Return d.GetImplementationValue(Of Global.LightSwitchApplication.Person, Global.LightSwitchApplication.Person.DetailsClass)(__ProjectAndProgram.DetailsClass.PropertySetProperties.Person, d._Person)
                End Function
                Private Shared Sub _Person_SetImplementationValue(d As __ProjectAndProgram.DetailsClass, v As Global.LightSwitchApplication.Person)
                    d.SetImplementationValue(__ProjectAndProgram.DetailsClass.PropertySetProperties.Person, d._Person, Sub(i, ev) i.Person = ev, v)
                End Sub
                Private Shared Sub _Person_Refresh(d As __ProjectAndProgram.DetailsClass)
                    d.RefreshNavigationProperty(__ProjectAndProgram.DetailsClass.PropertySetProperties.Person, d._Person)
                End Sub
                Private Shared Sub _Person_OnValueChanged(e As __ProjectAndProgram)
                    e.Person_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Person1 As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, Global.LightSwitchApplication.Person).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, Global.LightSwitchApplication.Person).Entry( _
                        "Person1", _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._Person1_Stub, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._Person1_ComputeIsReadOnly, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._Person1_Validate, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._Person1_GetCoreImplementationValue, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._Person1_GetImplementationValue, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._Person1_SetImplementationValue, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._Person1_Refresh, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._Person1_OnValueChanged)
                Private Shared Sub _Person1_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __ProjectAndProgram.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, Global.LightSwitchApplication.Person).Data), d As __ProjectAndProgram.DetailsClass, sf As Object)
                    c(d, d._Person1, sf)
                End Sub
                Private Shared Function _Person1_ComputeIsReadOnly(e As __ProjectAndProgram) As Boolean
                    Dim result As Boolean = False
                    e.Person1_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Person1_Validate(e As __ProjectAndProgram, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Person1_Validate(r)
                End Sub
                Private Shared Function _Person1_GetCoreImplementationValue(d as __ProjectAndProgram.DetailsClass) As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
                    Return d.ImplementationEntity.Person1
                End Function
                Private Shared Function _Person1_GetImplementationValue(d as __ProjectAndProgram.DetailsClass) As Global.LightSwitchApplication.Person
                    Return d.GetImplementationValue(Of Global.LightSwitchApplication.Person, Global.LightSwitchApplication.Person.DetailsClass)(__ProjectAndProgram.DetailsClass.PropertySetProperties.Person1, d._Person1)
                End Function
                Private Shared Sub _Person1_SetImplementationValue(d As __ProjectAndProgram.DetailsClass, v As Global.LightSwitchApplication.Person)
                    d.SetImplementationValue(__ProjectAndProgram.DetailsClass.PropertySetProperties.Person1, d._Person1, Sub(i, ev) i.Person1 = ev, v)
                End Sub
                Private Shared Sub _Person1_Refresh(d As __ProjectAndProgram.DetailsClass)
                    d.RefreshNavigationProperty(__ProjectAndProgram.DetailsClass.PropertySetProperties.Person1, d._Person1)
                End Sub
                Private Shared Sub _Person1_OnValueChanged(e As __ProjectAndProgram)
                    e.Person1_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly WorkGroup As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, Global.LightSwitchApplication.WorkGroup).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, Global.LightSwitchApplication.WorkGroup).Entry( _
                        "WorkGroup", _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._WorkGroup_Stub, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._WorkGroup_ComputeIsReadOnly, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._WorkGroup_Validate, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._WorkGroup_GetCoreImplementationValue, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._WorkGroup_GetImplementationValue, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._WorkGroup_SetImplementationValue, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._WorkGroup_Refresh, _
                        AddressOf __ProjectAndProgram.DetailsClass.PropertySetProperties._WorkGroup_OnValueChanged)
                Private Shared Sub _WorkGroup_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __ProjectAndProgram.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, Global.LightSwitchApplication.WorkGroup).Data), d As __ProjectAndProgram.DetailsClass, sf As Object)
                    c(d, d._WorkGroup, sf)
                End Sub
                Private Shared Function _WorkGroup_ComputeIsReadOnly(e As __ProjectAndProgram) As Boolean
                    Dim result As Boolean = False
                    e.WorkGroup_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _WorkGroup_Validate(e As __ProjectAndProgram, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.WorkGroup_Validate(r)
                End Sub
                Private Shared Function _WorkGroup_GetCoreImplementationValue(d as __ProjectAndProgram.DetailsClass) As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
                    Return d.ImplementationEntity.WorkGroup
                End Function
                Private Shared Function _WorkGroup_GetImplementationValue(d as __ProjectAndProgram.DetailsClass) As Global.LightSwitchApplication.WorkGroup
                    Return d.GetImplementationValue(Of Global.LightSwitchApplication.WorkGroup, Global.LightSwitchApplication.WorkGroup.DetailsClass)(__ProjectAndProgram.DetailsClass.PropertySetProperties.WorkGroup, d._WorkGroup)
                End Function
                Private Shared Sub _WorkGroup_SetImplementationValue(d As __ProjectAndProgram.DetailsClass, v As Global.LightSwitchApplication.WorkGroup)
                    d.SetImplementationValue(__ProjectAndProgram.DetailsClass.PropertySetProperties.WorkGroup, d._WorkGroup, Sub(i, ev) i.WorkGroup = ev, v)
                End Sub
                Private Shared Sub _WorkGroup_Refresh(d As __ProjectAndProgram.DetailsClass)
                    d.RefreshNavigationProperty(__ProjectAndProgram.DetailsClass.PropertySetProperties.WorkGroup, d._WorkGroup)
                End Sub
                Private Shared Sub _WorkGroup_OnValueChanged(e As __ProjectAndProgram)
                    e.WorkGroup_Changed()
                End Sub
    
            End Class
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _ID As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, Integer).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _ProjectOrProgram_ID As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _CommonName As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _ADSName As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _ProgTypeID As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, Global.System.Nullable(Of Integer)).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _as_Project_MonitoringStations As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, Global.LightSwitchApplication.as_Project_MonitoringStation).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Person As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, Global.LightSwitchApplication.Person).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Person1 As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, Global.LightSwitchApplication.Person).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _WorkGroup As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __ProjectAndProgram, __ProjectAndProgram.DetailsClass, Global.LightSwitchApplication.WorkGroup).Data
            
        End Class
    
        #End Region
    
    End Class
    
    #End Region
End Namespace
