
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports __CSFacility = LightSwitchApplication.CSFacility

Namespace LightSwitchApplication

    #Region "Entities"
    
    ''' <summary>
    ''' No Modeled Description Available
    ''' </summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
    Public NotInheritable Partial Class CSFacility
        Inherits Global.Microsoft.LightSwitch.Framework.Base.EntityObject(Of __CSFacility, __CSFacility.DetailsClass)
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Initializes a new instance of the CSFacility entity.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New()
            Me.New(Nothing)
        End Sub
    
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New(entitySet As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __CSFacility))
            MyBase.New(entitySet)
            
            __CSFacility.DetailsClass.Initialize(Me)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CSFacility_Created()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CSFacility_AllowSaveWithErrors(ByRef result As Boolean)
        End Sub
    
        #End Region
    
        #Region "Private Properties"
        
        ''' <summary>
        ''' Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property Application As Global.Microsoft.LightSwitch.IApplication(Of Global.LightSwitchApplication.DataWorkspace)
            Get
                Return Global.LightSwitchApplication.Application.Current
            End Get
        End Property
        
        ''' <summary>
        ''' Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property DataWorkspace As Global.LightSwitchApplication.DataWorkspace
            Get
                Return DirectCast(Me.Details.EntitySet.Details.DataService.Details.DataWorkspace, Global.LightSwitchApplication.DataWorkspace)
            End Get
        End Property
        
        #End Region
    
        #Region "Public Properties"
    
        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property ID_CSF As Integer
            Get
                Return __CSFacility.DetailsClass.GetValue(Me, __CSFacility.DetailsClass.PropertySetProperties.ID_CSF)
            End Get
            Set
                __CSFacility.DetailsClass.SetValue(Me, __CSFacility.DetailsClass.PropertySetProperties.ID_CSF, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ID_CSF_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ID_CSF_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ID_CSF_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property CSFacilityCode As String
            Get
                Return __CSFacility.DetailsClass.GetValue(Me, __CSFacility.DetailsClass.PropertySetProperties.CSFacilityCode)
            End Get
            Set
                __CSFacility.DetailsClass.SetValue(Me, __CSFacility.DetailsClass.PropertySetProperties.CSFacilityCode, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CSFacilityCode_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CSFacilityCode_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CSFacilityCode_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property NumberCode As Global.System.Nullable(Of Short)
            Get
                Return __CSFacility.DetailsClass.GetValue(Me, __CSFacility.DetailsClass.PropertySetProperties.NumberCode)
            End Get
            Set
                __CSFacility.DetailsClass.SetValue(Me, __CSFacility.DetailsClass.PropertySetProperties.NumberCode, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub NumberCode_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub NumberCode_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub NumberCode_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property AlternateName As String
            Get
                Return __CSFacility.DetailsClass.GetValue(Me, __CSFacility.DetailsClass.PropertySetProperties.AlternateName)
            End Get
            Set
                __CSFacility.DetailsClass.SetValue(Me, __CSFacility.DetailsClass.PropertySetProperties.AlternateName, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub AlternateName_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub AlternateName_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub AlternateName_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Hydrobrake As Boolean
            Get
                Return __CSFacility.DetailsClass.GetValue(Me, __CSFacility.DetailsClass.PropertySetProperties.Hydrobrake)
            End Get
            Set
                __CSFacility.DetailsClass.SetValue(Me, __CSFacility.DetailsClass.PropertySetProperties.Hydrobrake, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Hydrobrake_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Hydrobrake_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Hydrobrake_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Notes As String
            Get
                Return __CSFacility.DetailsClass.GetValue(Me, __CSFacility.DetailsClass.PropertySetProperties.Notes)
            End Get
            Set
                __CSFacility.DetailsClass.SetValue(Me, __CSFacility.DetailsClass.PropertySetProperties.Notes, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Notes_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Notes_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Notes_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property as_CSF_MonitoringStations As Global.Microsoft.LightSwitch.Framework.EntityCollection(Of Global.LightSwitchApplication.as_CSF_MonitoringStation)
            Get
                Return __CSFacility.DetailsClass.GetValue(Me, __CSFacility.DetailsClass.PropertySetProperties.as_CSF_MonitoringStations)
            End Get
        End Property
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property as_CSF_MonitoringStationsQuery As Microsoft.LightSwitch.IDataServiceQueryable(Of Global.LightSwitchApplication.as_CSF_MonitoringStation)
            Get
                Return __CSFacility.DetailsClass.GetQuery(Me, __CSFacility.DetailsClass.PropertySetProperties.as_CSF_MonitoringStations)
            End Get
        End Property

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property rt_CSFType As Global.LightSwitchApplication.rt_CSFType
            Get
                Return __CSFacility.DetailsClass.GetValue(Me, __CSFacility.DetailsClass.PropertySetProperties.rt_CSFType)
            End Get
            Set
                __CSFacility.DetailsClass.SetValue(Me, __CSFacility.DetailsClass.PropertySetProperties.rt_CSFType, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub rt_CSFType_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub rt_CSFType_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub rt_CSFType_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property rt_System As Global.LightSwitchApplication.rt_System
            Get
                Return __CSFacility.DetailsClass.GetValue(Me, __CSFacility.DetailsClass.PropertySetProperties.rt_System)
            End Get
            Set
                __CSFacility.DetailsClass.SetValue(Me, __CSFacility.DetailsClass.PropertySetProperties.rt_System, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub rt_System_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub rt_System_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub rt_System_Changed()
        End Sub

        #End Region
    
        #Region "Details Class"
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of _
                __CSFacility, _
                __CSFacility.DetailsClass, _
                __CSFacility.DetailsClass.IImplementation, _
                __CSFacility.DetailsClass.PropertySet, _
                Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __CSFacility, __CSFacility.DetailsClass), _
                Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __CSFacility, __CSFacility.DetailsClass))
    
            Shared Sub New()
                Dim initializeEntry = __CSFacility.DetailsClass.PropertySetProperties.ID_CSF
            End Sub
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private Shared ReadOnly __CSFacilityEntry As Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __CSFacility, __CSFacility.DetailsClass).Entry = _
                New Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __CSFacility, __CSFacility.DetailsClass).Entry( _
                    AddressOf __CSFacility.DetailsClass.__CSFacility_CreateNew, _
                    AddressOf __CSFacility.DetailsClass.__CSFacility_Created, _
                    AddressOf __CSFacility.DetailsClass.__CSFacility_AllowSaveWithErrors)
            Private Shared Function __CSFacility_CreateNew(es As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __CSFacility)) As __CSFacility
                Return New __CSFacility(es)
            End Function
            Private Shared Sub __CSFacility_Created(e As __CSFacility)
                e.CSFacility_Created()
            End Sub
            Private Shared Function __CSFacility_AllowSaveWithErrors(e As __CSFacility) As Boolean
                Dim result As Boolean = False
                e.CSFacility_AllowSaveWithErrors(result)
                Return result
            End Function
    
            Public Sub New()
                MyBase.New()
            End Sub
    
            Public ReadOnly Shadows Property Commands As Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __CSFacility, __CSFacility.DetailsClass)
                Get
                    Return MyBase.Commands
                End Get
            End Property
    
            Public ReadOnly Shadows Property Methods As Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __CSFacility, __CSFacility.DetailsClass)
                Get
                    Return MyBase.Methods
                End Get
            End Property
    
            Public ReadOnly Shadows Property Properties As __CSFacility.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet(Of __CSFacility, __CSFacility.DetailsClass)
    
                Public Sub New()
                    MyBase.New()
                End Sub
    
                Public ReadOnly Property ID_CSF As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CSFacility, __CSFacility.DetailsClass, Integer)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__CSFacility.DetailsClass.PropertySetProperties.ID_CSF),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CSFacility, __CSFacility.DetailsClass, Integer))
                    End Get
                End Property
                
                Public ReadOnly Property CSFacilityCode As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CSFacility, __CSFacility.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__CSFacility.DetailsClass.PropertySetProperties.CSFacilityCode),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CSFacility, __CSFacility.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property NumberCode As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CSFacility, __CSFacility.DetailsClass, Global.System.Nullable(Of Short))
                    Get
                        Return TryCast(
                            MyBase.GetItem(__CSFacility.DetailsClass.PropertySetProperties.NumberCode),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CSFacility, __CSFacility.DetailsClass, Global.System.Nullable(Of Short)))
                    End Get
                End Property
                
                Public ReadOnly Property AlternateName As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CSFacility, __CSFacility.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__CSFacility.DetailsClass.PropertySetProperties.AlternateName),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CSFacility, __CSFacility.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Hydrobrake As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CSFacility, __CSFacility.DetailsClass, Boolean)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__CSFacility.DetailsClass.PropertySetProperties.Hydrobrake),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CSFacility, __CSFacility.DetailsClass, Boolean))
                    End Get
                End Property
                
                Public ReadOnly Property Notes As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CSFacility, __CSFacility.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__CSFacility.DetailsClass.PropertySetProperties.Notes),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CSFacility, __CSFacility.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property as_CSF_MonitoringStations As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __CSFacility, __CSFacility.DetailsClass, Global.LightSwitchApplication.as_CSF_MonitoringStation)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__CSFacility.DetailsClass.PropertySetProperties.as_CSF_MonitoringStations),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __CSFacility, __CSFacility.DetailsClass, Global.LightSwitchApplication.as_CSF_MonitoringStation))
                    End Get
                End Property
                
                Public ReadOnly Property rt_CSFType As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __CSFacility, __CSFacility.DetailsClass, Global.LightSwitchApplication.rt_CSFType)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__CSFacility.DetailsClass.PropertySetProperties.rt_CSFType),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __CSFacility, __CSFacility.DetailsClass, Global.LightSwitchApplication.rt_CSFType))
                    End Get
                End Property
                
                Public ReadOnly Property rt_System As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __CSFacility, __CSFacility.DetailsClass, Global.LightSwitchApplication.rt_System)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__CSFacility.DetailsClass.PropertySetProperties.rt_System),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __CSFacility, __CSFacility.DetailsClass, Global.LightSwitchApplication.rt_System))
                    End Get
                End Property
                
            End Class
    
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            Public Interface IImplementation
                Inherits Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
                Shadows Property ID_CSF As Integer
                Shadows Property CSFacilityCode As String
                Shadows Property NumberCode As Global.System.Nullable(Of Short)
                Shadows Property AlternateName As String
                Shadows Property Hydrobrake As Boolean
                Shadows Property Notes As String
                Shadows ReadOnly Property as_CSF_MonitoringStations As Global.System.Collections.IEnumerable
                Shadows Property rt_CSFType As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
                Shadows Property rt_System As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
            End Interface
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend Class PropertySetProperties
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly ID_CSF As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CSFacility, __CSFacility.DetailsClass, Integer).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CSFacility, __CSFacility.DetailsClass, Integer).Entry( _
                        "ID_CSF", _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._ID_CSF_Stub, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._ID_CSF_ComputeIsReadOnly, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._ID_CSF_Validate, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._ID_CSF_GetImplementationValue, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._ID_CSF_SetImplementationValue, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._ID_CSF_OnValueChanged)
                Private Shared Sub _ID_CSF_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __CSFacility.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CSFacility, __CSFacility.DetailsClass, Integer).Data), d As __CSFacility.DetailsClass, sf As Object)
                    c(d, d._ID_CSF, sf)
                End Sub
                Private Shared Function _ID_CSF_ComputeIsReadOnly(e As __CSFacility) As Boolean
                    Dim result As Boolean = False
                    e.ID_CSF_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _ID_CSF_Validate(e As __CSFacility, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.ID_CSF_Validate(r)
                End Sub
                Private Shared Function _ID_CSF_GetImplementationValue(d As __CSFacility.DetailsClass) As Integer
                    Return d.ImplementationEntity.ID_CSF
                End Function
                Private Shared Sub _ID_CSF_SetImplementationValue(d As __CSFacility.DetailsClass, v As Integer)
                    d.ImplementationEntity.ID_CSF = v
                End Sub
                Private Shared Sub _ID_CSF_OnValueChanged(e As __CSFacility)
                    e.ID_CSF_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly CSFacilityCode As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CSFacility, __CSFacility.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CSFacility, __CSFacility.DetailsClass, String).Entry( _
                        "CSFacilityCode", _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._CSFacilityCode_Stub, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._CSFacilityCode_ComputeIsReadOnly, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._CSFacilityCode_Validate, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._CSFacilityCode_GetImplementationValue, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._CSFacilityCode_SetImplementationValue, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._CSFacilityCode_OnValueChanged)
                Private Shared Sub _CSFacilityCode_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __CSFacility.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CSFacility, __CSFacility.DetailsClass, String).Data), d As __CSFacility.DetailsClass, sf As Object)
                    c(d, d._CSFacilityCode, sf)
                End Sub
                Private Shared Function _CSFacilityCode_ComputeIsReadOnly(e As __CSFacility) As Boolean
                    Dim result As Boolean = False
                    e.CSFacilityCode_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _CSFacilityCode_Validate(e As __CSFacility, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.CSFacilityCode_Validate(r)
                End Sub
                Private Shared Function _CSFacilityCode_GetImplementationValue(d As __CSFacility.DetailsClass) As String
                    Return d.ImplementationEntity.CSFacilityCode
                End Function
                Private Shared Sub _CSFacilityCode_SetImplementationValue(d As __CSFacility.DetailsClass, v As String)
                    d.ImplementationEntity.CSFacilityCode = v
                End Sub
                Private Shared Sub _CSFacilityCode_OnValueChanged(e As __CSFacility)
                    e.CSFacilityCode_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly NumberCode As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CSFacility, __CSFacility.DetailsClass, Global.System.Nullable(Of Short)).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CSFacility, __CSFacility.DetailsClass, Global.System.Nullable(Of Short)).Entry( _
                        "NumberCode", _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._NumberCode_Stub, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._NumberCode_ComputeIsReadOnly, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._NumberCode_Validate, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._NumberCode_GetImplementationValue, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._NumberCode_SetImplementationValue, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._NumberCode_OnValueChanged)
                Private Shared Sub _NumberCode_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __CSFacility.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CSFacility, __CSFacility.DetailsClass, Global.System.Nullable(Of Short)).Data), d As __CSFacility.DetailsClass, sf As Object)
                    c(d, d._NumberCode, sf)
                End Sub
                Private Shared Function _NumberCode_ComputeIsReadOnly(e As __CSFacility) As Boolean
                    Dim result As Boolean = False
                    e.NumberCode_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _NumberCode_Validate(e As __CSFacility, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.NumberCode_Validate(r)
                End Sub
                Private Shared Function _NumberCode_GetImplementationValue(d As __CSFacility.DetailsClass) As Global.System.Nullable(Of Short)
                    Return d.ImplementationEntity.NumberCode
                End Function
                Private Shared Sub _NumberCode_SetImplementationValue(d As __CSFacility.DetailsClass, v As Global.System.Nullable(Of Short))
                    d.ImplementationEntity.NumberCode = v
                End Sub
                Private Shared Sub _NumberCode_OnValueChanged(e As __CSFacility)
                    e.NumberCode_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly AlternateName As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CSFacility, __CSFacility.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CSFacility, __CSFacility.DetailsClass, String).Entry( _
                        "AlternateName", _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._AlternateName_Stub, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._AlternateName_ComputeIsReadOnly, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._AlternateName_Validate, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._AlternateName_GetImplementationValue, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._AlternateName_SetImplementationValue, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._AlternateName_OnValueChanged)
                Private Shared Sub _AlternateName_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __CSFacility.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CSFacility, __CSFacility.DetailsClass, String).Data), d As __CSFacility.DetailsClass, sf As Object)
                    c(d, d._AlternateName, sf)
                End Sub
                Private Shared Function _AlternateName_ComputeIsReadOnly(e As __CSFacility) As Boolean
                    Dim result As Boolean = False
                    e.AlternateName_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _AlternateName_Validate(e As __CSFacility, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.AlternateName_Validate(r)
                End Sub
                Private Shared Function _AlternateName_GetImplementationValue(d As __CSFacility.DetailsClass) As String
                    Return d.ImplementationEntity.AlternateName
                End Function
                Private Shared Sub _AlternateName_SetImplementationValue(d As __CSFacility.DetailsClass, v As String)
                    d.ImplementationEntity.AlternateName = v
                End Sub
                Private Shared Sub _AlternateName_OnValueChanged(e As __CSFacility)
                    e.AlternateName_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Hydrobrake As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CSFacility, __CSFacility.DetailsClass, Boolean).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CSFacility, __CSFacility.DetailsClass, Boolean).Entry( _
                        "Hydrobrake", _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._Hydrobrake_Stub, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._Hydrobrake_ComputeIsReadOnly, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._Hydrobrake_Validate, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._Hydrobrake_GetImplementationValue, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._Hydrobrake_SetImplementationValue, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._Hydrobrake_OnValueChanged)
                Private Shared Sub _Hydrobrake_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __CSFacility.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CSFacility, __CSFacility.DetailsClass, Boolean).Data), d As __CSFacility.DetailsClass, sf As Object)
                    c(d, d._Hydrobrake, sf)
                End Sub
                Private Shared Function _Hydrobrake_ComputeIsReadOnly(e As __CSFacility) As Boolean
                    Dim result As Boolean = False
                    e.Hydrobrake_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Hydrobrake_Validate(e As __CSFacility, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Hydrobrake_Validate(r)
                End Sub
                Private Shared Function _Hydrobrake_GetImplementationValue(d As __CSFacility.DetailsClass) As Boolean
                    Return d.ImplementationEntity.Hydrobrake
                End Function
                Private Shared Sub _Hydrobrake_SetImplementationValue(d As __CSFacility.DetailsClass, v As Boolean)
                    d.ImplementationEntity.Hydrobrake = v
                End Sub
                Private Shared Sub _Hydrobrake_OnValueChanged(e As __CSFacility)
                    e.Hydrobrake_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Notes As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CSFacility, __CSFacility.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CSFacility, __CSFacility.DetailsClass, String).Entry( _
                        "Notes", _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._Notes_Stub, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._Notes_ComputeIsReadOnly, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._Notes_Validate, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._Notes_GetImplementationValue, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._Notes_SetImplementationValue, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._Notes_OnValueChanged)
                Private Shared Sub _Notes_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __CSFacility.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CSFacility, __CSFacility.DetailsClass, String).Data), d As __CSFacility.DetailsClass, sf As Object)
                    c(d, d._Notes, sf)
                End Sub
                Private Shared Function _Notes_ComputeIsReadOnly(e As __CSFacility) As Boolean
                    Dim result As Boolean = False
                    e.Notes_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Notes_Validate(e As __CSFacility, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Notes_Validate(r)
                End Sub
                Private Shared Function _Notes_GetImplementationValue(d As __CSFacility.DetailsClass) As String
                    Return d.ImplementationEntity.Notes
                End Function
                Private Shared Sub _Notes_SetImplementationValue(d As __CSFacility.DetailsClass, v As String)
                    d.ImplementationEntity.Notes = v
                End Sub
                Private Shared Sub _Notes_OnValueChanged(e As __CSFacility)
                    e.Notes_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly as_CSF_MonitoringStations As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __CSFacility, __CSFacility.DetailsClass, Global.LightSwitchApplication.as_CSF_MonitoringStation).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __CSFacility, __CSFacility.DetailsClass, Global.LightSwitchApplication.as_CSF_MonitoringStation).Entry( _
                        "as_CSF_MonitoringStations", _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._as_CSF_MonitoringStations_Stub, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._as_CSF_MonitoringStations_GetReferencedEntities, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._as_CSF_MonitoringStations_GetEntityCollection)
                Private Shared Sub _as_CSF_MonitoringStations_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __CSFacility.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __CSFacility, __CSFacility.DetailsClass, Global.LightSwitchApplication.as_CSF_MonitoringStation).Data), d As __CSFacility.DetailsClass, sf As Object)
                    c(d, d._as_CSF_MonitoringStations, sf)
                End Sub
                Private Shared Function _as_CSF_MonitoringStations_GetReferencedEntities(d As __CSFacility.DetailsClass) As Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.as_CSF_MonitoringStation)
                    Return d.GetReferencedEntities(Of Global.LightSwitchApplication.as_CSF_MonitoringStation, Global.LightSwitchApplication.as_CSF_MonitoringStation.DetailsClass)(__CSFacility.DetailsClass.PropertySetProperties.as_CSF_MonitoringStations, d._as_CSF_MonitoringStations)
                End Function
                Private Shared Function _as_CSF_MonitoringStations_GetEntityCollection(d As __CSFacility.DetailsClass) As Global.System.Collections.IEnumerable
                    Return d.ImplementationEntity.as_CSF_MonitoringStations
                End Function
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly rt_CSFType As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __CSFacility, __CSFacility.DetailsClass, Global.LightSwitchApplication.rt_CSFType).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __CSFacility, __CSFacility.DetailsClass, Global.LightSwitchApplication.rt_CSFType).Entry( _
                        "rt_CSFType", _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._rt_CSFType_Stub, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._rt_CSFType_ComputeIsReadOnly, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._rt_CSFType_Validate, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._rt_CSFType_GetCoreImplementationValue, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._rt_CSFType_GetImplementationValue, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._rt_CSFType_SetImplementationValue, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._rt_CSFType_Refresh, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._rt_CSFType_OnValueChanged)
                Private Shared Sub _rt_CSFType_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __CSFacility.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __CSFacility, __CSFacility.DetailsClass, Global.LightSwitchApplication.rt_CSFType).Data), d As __CSFacility.DetailsClass, sf As Object)
                    c(d, d._rt_CSFType, sf)
                End Sub
                Private Shared Function _rt_CSFType_ComputeIsReadOnly(e As __CSFacility) As Boolean
                    Dim result As Boolean = False
                    e.rt_CSFType_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _rt_CSFType_Validate(e As __CSFacility, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.rt_CSFType_Validate(r)
                End Sub
                Private Shared Function _rt_CSFType_GetCoreImplementationValue(d as __CSFacility.DetailsClass) As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
                    Return d.ImplementationEntity.rt_CSFType
                End Function
                Private Shared Function _rt_CSFType_GetImplementationValue(d as __CSFacility.DetailsClass) As Global.LightSwitchApplication.rt_CSFType
                    Return d.GetImplementationValue(Of Global.LightSwitchApplication.rt_CSFType, Global.LightSwitchApplication.rt_CSFType.DetailsClass)(__CSFacility.DetailsClass.PropertySetProperties.rt_CSFType, d._rt_CSFType)
                End Function
                Private Shared Sub _rt_CSFType_SetImplementationValue(d As __CSFacility.DetailsClass, v As Global.LightSwitchApplication.rt_CSFType)
                    d.SetImplementationValue(__CSFacility.DetailsClass.PropertySetProperties.rt_CSFType, d._rt_CSFType, Sub(i, ev) i.rt_CSFType = ev, v)
                End Sub
                Private Shared Sub _rt_CSFType_Refresh(d As __CSFacility.DetailsClass)
                    d.RefreshNavigationProperty(__CSFacility.DetailsClass.PropertySetProperties.rt_CSFType, d._rt_CSFType)
                End Sub
                Private Shared Sub _rt_CSFType_OnValueChanged(e As __CSFacility)
                    e.rt_CSFType_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly rt_System As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __CSFacility, __CSFacility.DetailsClass, Global.LightSwitchApplication.rt_System).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __CSFacility, __CSFacility.DetailsClass, Global.LightSwitchApplication.rt_System).Entry( _
                        "rt_System", _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._rt_System_Stub, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._rt_System_ComputeIsReadOnly, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._rt_System_Validate, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._rt_System_GetCoreImplementationValue, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._rt_System_GetImplementationValue, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._rt_System_SetImplementationValue, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._rt_System_Refresh, _
                        AddressOf __CSFacility.DetailsClass.PropertySetProperties._rt_System_OnValueChanged)
                Private Shared Sub _rt_System_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __CSFacility.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __CSFacility, __CSFacility.DetailsClass, Global.LightSwitchApplication.rt_System).Data), d As __CSFacility.DetailsClass, sf As Object)
                    c(d, d._rt_System, sf)
                End Sub
                Private Shared Function _rt_System_ComputeIsReadOnly(e As __CSFacility) As Boolean
                    Dim result As Boolean = False
                    e.rt_System_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _rt_System_Validate(e As __CSFacility, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.rt_System_Validate(r)
                End Sub
                Private Shared Function _rt_System_GetCoreImplementationValue(d as __CSFacility.DetailsClass) As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
                    Return d.ImplementationEntity.rt_System
                End Function
                Private Shared Function _rt_System_GetImplementationValue(d as __CSFacility.DetailsClass) As Global.LightSwitchApplication.rt_System
                    Return d.GetImplementationValue(Of Global.LightSwitchApplication.rt_System, Global.LightSwitchApplication.rt_System.DetailsClass)(__CSFacility.DetailsClass.PropertySetProperties.rt_System, d._rt_System)
                End Function
                Private Shared Sub _rt_System_SetImplementationValue(d As __CSFacility.DetailsClass, v As Global.LightSwitchApplication.rt_System)
                    d.SetImplementationValue(__CSFacility.DetailsClass.PropertySetProperties.rt_System, d._rt_System, Sub(i, ev) i.rt_System = ev, v)
                End Sub
                Private Shared Sub _rt_System_Refresh(d As __CSFacility.DetailsClass)
                    d.RefreshNavigationProperty(__CSFacility.DetailsClass.PropertySetProperties.rt_System, d._rt_System)
                End Sub
                Private Shared Sub _rt_System_OnValueChanged(e As __CSFacility)
                    e.rt_System_Changed()
                End Sub
    
            End Class
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _ID_CSF As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CSFacility, __CSFacility.DetailsClass, Integer).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _CSFacilityCode As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CSFacility, __CSFacility.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _NumberCode As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CSFacility, __CSFacility.DetailsClass, Global.System.Nullable(Of Short)).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _AlternateName As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CSFacility, __CSFacility.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Hydrobrake As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CSFacility, __CSFacility.DetailsClass, Boolean).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Notes As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CSFacility, __CSFacility.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _as_CSF_MonitoringStations As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __CSFacility, __CSFacility.DetailsClass, Global.LightSwitchApplication.as_CSF_MonitoringStation).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _rt_CSFType As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __CSFacility, __CSFacility.DetailsClass, Global.LightSwitchApplication.rt_CSFType).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _rt_System As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __CSFacility, __CSFacility.DetailsClass, Global.LightSwitchApplication.rt_System).Data
            
        End Class
    
        #End Region
    
    End Class
    
    #End Region
End Namespace
