
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports __as_RainGage_MonitoringStation = LightSwitchApplication.as_RainGage_MonitoringStation

Namespace LightSwitchApplication

    #Region "Entities"
    
    ''' <summary>
    ''' No Modeled Description Available
    ''' </summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
    Public NotInheritable Partial Class as_RainGage_MonitoringStation
        Inherits Global.Microsoft.LightSwitch.Framework.Base.EntityObject(Of __as_RainGage_MonitoringStation, __as_RainGage_MonitoringStation.DetailsClass)
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Initializes a new instance of the as_RainGage_MonitoringStation entity.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New()
            Me.New(Nothing)
        End Sub
    
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New(entitySet As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __as_RainGage_MonitoringStation))
            MyBase.New(entitySet)
            
            __as_RainGage_MonitoringStation.DetailsClass.Initialize(Me)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub as_RainGage_MonitoringStation_Created()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub as_RainGage_MonitoringStation_AllowSaveWithErrors(ByRef result As Boolean)
        End Sub
    
        #End Region
    
        #Region "Private Properties"
        
        ''' <summary>
        ''' Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property Application As Global.Microsoft.LightSwitch.IApplication(Of Global.LightSwitchApplication.DataWorkspace)
            Get
                Return Global.LightSwitchApplication.Application.Current
            End Get
        End Property
        
        ''' <summary>
        ''' Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property DataWorkspace As Global.LightSwitchApplication.DataWorkspace
            Get
                Return DirectCast(Me.Details.EntitySet.Details.DataService.Details.DataWorkspace, Global.LightSwitchApplication.DataWorkspace)
            End Get
        End Property
        
        #End Region
    
        #Region "Public Properties"
    
        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property ID As Integer
            Get
                Return __as_RainGage_MonitoringStation.DetailsClass.GetValue(Me, __as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties.ID)
            End Get
            Set
                __as_RainGage_MonitoringStation.DetailsClass.SetValue(Me, __as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties.ID, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ID_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ID_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ID_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property MonitoringStation1 As Global.LightSwitchApplication.MonitoringStation
            Get
                Return __as_RainGage_MonitoringStation.DetailsClass.GetValue(Me, __as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties.MonitoringStation1)
            End Get
            Set
                __as_RainGage_MonitoringStation.DetailsClass.SetValue(Me, __as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties.MonitoringStation1, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub MonitoringStation1_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub MonitoringStation1_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub MonitoringStation1_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property RainGage1 As Global.LightSwitchApplication.RainGage
            Get
                Return __as_RainGage_MonitoringStation.DetailsClass.GetValue(Me, __as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties.RainGage1)
            End Get
            Set
                __as_RainGage_MonitoringStation.DetailsClass.SetValue(Me, __as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties.RainGage1, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub RainGage1_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub RainGage1_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub RainGage1_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property rt_Relationship As Global.LightSwitchApplication.rt_Relationship
            Get
                Return __as_RainGage_MonitoringStation.DetailsClass.GetValue(Me, __as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties.rt_Relationship)
            End Get
            Set
                __as_RainGage_MonitoringStation.DetailsClass.SetValue(Me, __as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties.rt_Relationship, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub rt_Relationship_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub rt_Relationship_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub rt_Relationship_Changed()
        End Sub

        #End Region
    
        #Region "Details Class"
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of _
                __as_RainGage_MonitoringStation, _
                __as_RainGage_MonitoringStation.DetailsClass, _
                __as_RainGage_MonitoringStation.DetailsClass.IImplementation, _
                __as_RainGage_MonitoringStation.DetailsClass.PropertySet, _
                Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __as_RainGage_MonitoringStation, __as_RainGage_MonitoringStation.DetailsClass), _
                Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __as_RainGage_MonitoringStation, __as_RainGage_MonitoringStation.DetailsClass))
    
            Shared Sub New()
                Dim initializeEntry = __as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties.ID
            End Sub
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private Shared ReadOnly __as_RainGage_MonitoringStationEntry As Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __as_RainGage_MonitoringStation, __as_RainGage_MonitoringStation.DetailsClass).Entry = _
                New Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __as_RainGage_MonitoringStation, __as_RainGage_MonitoringStation.DetailsClass).Entry( _
                    AddressOf __as_RainGage_MonitoringStation.DetailsClass.__as_RainGage_MonitoringStation_CreateNew, _
                    AddressOf __as_RainGage_MonitoringStation.DetailsClass.__as_RainGage_MonitoringStation_Created, _
                    AddressOf __as_RainGage_MonitoringStation.DetailsClass.__as_RainGage_MonitoringStation_AllowSaveWithErrors)
            Private Shared Function __as_RainGage_MonitoringStation_CreateNew(es As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __as_RainGage_MonitoringStation)) As __as_RainGage_MonitoringStation
                Return New __as_RainGage_MonitoringStation(es)
            End Function
            Private Shared Sub __as_RainGage_MonitoringStation_Created(e As __as_RainGage_MonitoringStation)
                e.as_RainGage_MonitoringStation_Created()
            End Sub
            Private Shared Function __as_RainGage_MonitoringStation_AllowSaveWithErrors(e As __as_RainGage_MonitoringStation) As Boolean
                Dim result As Boolean = False
                e.as_RainGage_MonitoringStation_AllowSaveWithErrors(result)
                Return result
            End Function
    
            Public Sub New()
                MyBase.New()
            End Sub
    
            Public ReadOnly Shadows Property Commands As Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __as_RainGage_MonitoringStation, __as_RainGage_MonitoringStation.DetailsClass)
                Get
                    Return MyBase.Commands
                End Get
            End Property
    
            Public ReadOnly Shadows Property Methods As Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __as_RainGage_MonitoringStation, __as_RainGage_MonitoringStation.DetailsClass)
                Get
                    Return MyBase.Methods
                End Get
            End Property
    
            Public ReadOnly Shadows Property Properties As __as_RainGage_MonitoringStation.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet(Of __as_RainGage_MonitoringStation, __as_RainGage_MonitoringStation.DetailsClass)
    
                Public Sub New()
                    MyBase.New()
                End Sub
    
                Public ReadOnly Property ID As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __as_RainGage_MonitoringStation, __as_RainGage_MonitoringStation.DetailsClass, Integer)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties.ID),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __as_RainGage_MonitoringStation, __as_RainGage_MonitoringStation.DetailsClass, Integer))
                    End Get
                End Property
                
                Public ReadOnly Property MonitoringStation1 As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __as_RainGage_MonitoringStation, __as_RainGage_MonitoringStation.DetailsClass, Global.LightSwitchApplication.MonitoringStation)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties.MonitoringStation1),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __as_RainGage_MonitoringStation, __as_RainGage_MonitoringStation.DetailsClass, Global.LightSwitchApplication.MonitoringStation))
                    End Get
                End Property
                
                Public ReadOnly Property RainGage1 As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __as_RainGage_MonitoringStation, __as_RainGage_MonitoringStation.DetailsClass, Global.LightSwitchApplication.RainGage)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties.RainGage1),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __as_RainGage_MonitoringStation, __as_RainGage_MonitoringStation.DetailsClass, Global.LightSwitchApplication.RainGage))
                    End Get
                End Property
                
                Public ReadOnly Property rt_Relationship As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __as_RainGage_MonitoringStation, __as_RainGage_MonitoringStation.DetailsClass, Global.LightSwitchApplication.rt_Relationship)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties.rt_Relationship),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __as_RainGage_MonitoringStation, __as_RainGage_MonitoringStation.DetailsClass, Global.LightSwitchApplication.rt_Relationship))
                    End Get
                End Property
                
            End Class
    
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            Public Interface IImplementation
                Inherits Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
                Shadows Property ID As Integer
                Shadows Property MonitoringStation1 As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
                Shadows Property RainGage1 As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
                Shadows Property rt_Relationship As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
            End Interface
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend Class PropertySetProperties
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly ID As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __as_RainGage_MonitoringStation, __as_RainGage_MonitoringStation.DetailsClass, Integer).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __as_RainGage_MonitoringStation, __as_RainGage_MonitoringStation.DetailsClass, Integer).Entry( _
                        "ID", _
                        AddressOf __as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties._ID_Stub, _
                        AddressOf __as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties._ID_ComputeIsReadOnly, _
                        AddressOf __as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties._ID_Validate, _
                        AddressOf __as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties._ID_GetImplementationValue, _
                        AddressOf __as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties._ID_SetImplementationValue, _
                        AddressOf __as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties._ID_OnValueChanged)
                Private Shared Sub _ID_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __as_RainGage_MonitoringStation.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __as_RainGage_MonitoringStation, __as_RainGage_MonitoringStation.DetailsClass, Integer).Data), d As __as_RainGage_MonitoringStation.DetailsClass, sf As Object)
                    c(d, d._ID, sf)
                End Sub
                Private Shared Function _ID_ComputeIsReadOnly(e As __as_RainGage_MonitoringStation) As Boolean
                    Dim result As Boolean = False
                    e.ID_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _ID_Validate(e As __as_RainGage_MonitoringStation, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.ID_Validate(r)
                End Sub
                Private Shared Function _ID_GetImplementationValue(d As __as_RainGage_MonitoringStation.DetailsClass) As Integer
                    Return d.ImplementationEntity.ID
                End Function
                Private Shared Sub _ID_SetImplementationValue(d As __as_RainGage_MonitoringStation.DetailsClass, v As Integer)
                    d.ImplementationEntity.ID = v
                End Sub
                Private Shared Sub _ID_OnValueChanged(e As __as_RainGage_MonitoringStation)
                    e.ID_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly MonitoringStation1 As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __as_RainGage_MonitoringStation, __as_RainGage_MonitoringStation.DetailsClass, Global.LightSwitchApplication.MonitoringStation).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __as_RainGage_MonitoringStation, __as_RainGage_MonitoringStation.DetailsClass, Global.LightSwitchApplication.MonitoringStation).Entry( _
                        "MonitoringStation1", _
                        AddressOf __as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties._MonitoringStation1_Stub, _
                        AddressOf __as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties._MonitoringStation1_ComputeIsReadOnly, _
                        AddressOf __as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties._MonitoringStation1_Validate, _
                        AddressOf __as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties._MonitoringStation1_GetCoreImplementationValue, _
                        AddressOf __as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties._MonitoringStation1_GetImplementationValue, _
                        AddressOf __as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties._MonitoringStation1_SetImplementationValue, _
                        AddressOf __as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties._MonitoringStation1_Refresh, _
                        AddressOf __as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties._MonitoringStation1_OnValueChanged)
                Private Shared Sub _MonitoringStation1_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __as_RainGage_MonitoringStation.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __as_RainGage_MonitoringStation, __as_RainGage_MonitoringStation.DetailsClass, Global.LightSwitchApplication.MonitoringStation).Data), d As __as_RainGage_MonitoringStation.DetailsClass, sf As Object)
                    c(d, d._MonitoringStation1, sf)
                End Sub
                Private Shared Function _MonitoringStation1_ComputeIsReadOnly(e As __as_RainGage_MonitoringStation) As Boolean
                    Dim result As Boolean = False
                    e.MonitoringStation1_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _MonitoringStation1_Validate(e As __as_RainGage_MonitoringStation, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.MonitoringStation1_Validate(r)
                End Sub
                Private Shared Function _MonitoringStation1_GetCoreImplementationValue(d as __as_RainGage_MonitoringStation.DetailsClass) As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
                    Return d.ImplementationEntity.MonitoringStation1
                End Function
                Private Shared Function _MonitoringStation1_GetImplementationValue(d as __as_RainGage_MonitoringStation.DetailsClass) As Global.LightSwitchApplication.MonitoringStation
                    Return d.GetImplementationValue(Of Global.LightSwitchApplication.MonitoringStation, Global.LightSwitchApplication.MonitoringStation.DetailsClass)(__as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties.MonitoringStation1, d._MonitoringStation1)
                End Function
                Private Shared Sub _MonitoringStation1_SetImplementationValue(d As __as_RainGage_MonitoringStation.DetailsClass, v As Global.LightSwitchApplication.MonitoringStation)
                    d.SetImplementationValue(__as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties.MonitoringStation1, d._MonitoringStation1, Sub(i, ev) i.MonitoringStation1 = ev, v)
                End Sub
                Private Shared Sub _MonitoringStation1_Refresh(d As __as_RainGage_MonitoringStation.DetailsClass)
                    d.RefreshNavigationProperty(__as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties.MonitoringStation1, d._MonitoringStation1)
                End Sub
                Private Shared Sub _MonitoringStation1_OnValueChanged(e As __as_RainGage_MonitoringStation)
                    e.MonitoringStation1_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly RainGage1 As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __as_RainGage_MonitoringStation, __as_RainGage_MonitoringStation.DetailsClass, Global.LightSwitchApplication.RainGage).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __as_RainGage_MonitoringStation, __as_RainGage_MonitoringStation.DetailsClass, Global.LightSwitchApplication.RainGage).Entry( _
                        "RainGage1", _
                        AddressOf __as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties._RainGage1_Stub, _
                        AddressOf __as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties._RainGage1_ComputeIsReadOnly, _
                        AddressOf __as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties._RainGage1_Validate, _
                        AddressOf __as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties._RainGage1_GetCoreImplementationValue, _
                        AddressOf __as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties._RainGage1_GetImplementationValue, _
                        AddressOf __as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties._RainGage1_SetImplementationValue, _
                        AddressOf __as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties._RainGage1_Refresh, _
                        AddressOf __as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties._RainGage1_OnValueChanged)
                Private Shared Sub _RainGage1_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __as_RainGage_MonitoringStation.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __as_RainGage_MonitoringStation, __as_RainGage_MonitoringStation.DetailsClass, Global.LightSwitchApplication.RainGage).Data), d As __as_RainGage_MonitoringStation.DetailsClass, sf As Object)
                    c(d, d._RainGage1, sf)
                End Sub
                Private Shared Function _RainGage1_ComputeIsReadOnly(e As __as_RainGage_MonitoringStation) As Boolean
                    Dim result As Boolean = False
                    e.RainGage1_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _RainGage1_Validate(e As __as_RainGage_MonitoringStation, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.RainGage1_Validate(r)
                End Sub
                Private Shared Function _RainGage1_GetCoreImplementationValue(d as __as_RainGage_MonitoringStation.DetailsClass) As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
                    Return d.ImplementationEntity.RainGage1
                End Function
                Private Shared Function _RainGage1_GetImplementationValue(d as __as_RainGage_MonitoringStation.DetailsClass) As Global.LightSwitchApplication.RainGage
                    Return d.GetImplementationValue(Of Global.LightSwitchApplication.RainGage, Global.LightSwitchApplication.RainGage.DetailsClass)(__as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties.RainGage1, d._RainGage1)
                End Function
                Private Shared Sub _RainGage1_SetImplementationValue(d As __as_RainGage_MonitoringStation.DetailsClass, v As Global.LightSwitchApplication.RainGage)
                    d.SetImplementationValue(__as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties.RainGage1, d._RainGage1, Sub(i, ev) i.RainGage1 = ev, v)
                End Sub
                Private Shared Sub _RainGage1_Refresh(d As __as_RainGage_MonitoringStation.DetailsClass)
                    d.RefreshNavigationProperty(__as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties.RainGage1, d._RainGage1)
                End Sub
                Private Shared Sub _RainGage1_OnValueChanged(e As __as_RainGage_MonitoringStation)
                    e.RainGage1_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly rt_Relationship As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __as_RainGage_MonitoringStation, __as_RainGage_MonitoringStation.DetailsClass, Global.LightSwitchApplication.rt_Relationship).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __as_RainGage_MonitoringStation, __as_RainGage_MonitoringStation.DetailsClass, Global.LightSwitchApplication.rt_Relationship).Entry( _
                        "rt_Relationship", _
                        AddressOf __as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties._rt_Relationship_Stub, _
                        AddressOf __as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties._rt_Relationship_ComputeIsReadOnly, _
                        AddressOf __as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties._rt_Relationship_Validate, _
                        AddressOf __as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties._rt_Relationship_GetCoreImplementationValue, _
                        AddressOf __as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties._rt_Relationship_GetImplementationValue, _
                        AddressOf __as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties._rt_Relationship_SetImplementationValue, _
                        AddressOf __as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties._rt_Relationship_Refresh, _
                        AddressOf __as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties._rt_Relationship_OnValueChanged)
                Private Shared Sub _rt_Relationship_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __as_RainGage_MonitoringStation.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __as_RainGage_MonitoringStation, __as_RainGage_MonitoringStation.DetailsClass, Global.LightSwitchApplication.rt_Relationship).Data), d As __as_RainGage_MonitoringStation.DetailsClass, sf As Object)
                    c(d, d._rt_Relationship, sf)
                End Sub
                Private Shared Function _rt_Relationship_ComputeIsReadOnly(e As __as_RainGage_MonitoringStation) As Boolean
                    Dim result As Boolean = False
                    e.rt_Relationship_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _rt_Relationship_Validate(e As __as_RainGage_MonitoringStation, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.rt_Relationship_Validate(r)
                End Sub
                Private Shared Function _rt_Relationship_GetCoreImplementationValue(d as __as_RainGage_MonitoringStation.DetailsClass) As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
                    Return d.ImplementationEntity.rt_Relationship
                End Function
                Private Shared Function _rt_Relationship_GetImplementationValue(d as __as_RainGage_MonitoringStation.DetailsClass) As Global.LightSwitchApplication.rt_Relationship
                    Return d.GetImplementationValue(Of Global.LightSwitchApplication.rt_Relationship, Global.LightSwitchApplication.rt_Relationship.DetailsClass)(__as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties.rt_Relationship, d._rt_Relationship)
                End Function
                Private Shared Sub _rt_Relationship_SetImplementationValue(d As __as_RainGage_MonitoringStation.DetailsClass, v As Global.LightSwitchApplication.rt_Relationship)
                    d.SetImplementationValue(__as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties.rt_Relationship, d._rt_Relationship, Sub(i, ev) i.rt_Relationship = ev, v)
                End Sub
                Private Shared Sub _rt_Relationship_Refresh(d As __as_RainGage_MonitoringStation.DetailsClass)
                    d.RefreshNavigationProperty(__as_RainGage_MonitoringStation.DetailsClass.PropertySetProperties.rt_Relationship, d._rt_Relationship)
                End Sub
                Private Shared Sub _rt_Relationship_OnValueChanged(e As __as_RainGage_MonitoringStation)
                    e.rt_Relationship_Changed()
                End Sub
    
            End Class
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _ID As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __as_RainGage_MonitoringStation, __as_RainGage_MonitoringStation.DetailsClass, Integer).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _MonitoringStation1 As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __as_RainGage_MonitoringStation, __as_RainGage_MonitoringStation.DetailsClass, Global.LightSwitchApplication.MonitoringStation).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _RainGage1 As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __as_RainGage_MonitoringStation, __as_RainGage_MonitoringStation.DetailsClass, Global.LightSwitchApplication.RainGage).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _rt_Relationship As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __as_RainGage_MonitoringStation, __as_RainGage_MonitoringStation.DetailsClass, Global.LightSwitchApplication.rt_Relationship).Data
            
        End Class
    
        #End Region
    
    End Class
    
    #End Region
End Namespace
